/* This file is automatically generated from `obsd41.sc' with sc2int.
 * !!! DO NOT EDIT !!!
 */

#ifndef __obsd41_syscalls_h
#define __obsd41_syscalls_h

/* OpenBSD 4.1 System Calls Definitions */

#define OBSD41_SYS_last 306

/* syscall: "syscall" ret: "word" args: "word" "..." */
#define OBSD41_SYS_syscall 0

/* syscall: "exit" ret: "word" args: "word" */
#define OBSD41_SYS_exit 1

/* syscall: "fork" ret: "word" args: */
#define OBSD41_SYS_fork 2

/* syscall: "read" ret: "word" args: "word" "ptr" "word" */
#define OBSD41_SYS_read 3

/* syscall: "write" ret: "word" args: "word" "ptr" "word" */
#define OBSD41_SYS_write 4

/* syscall: "open" ret: "word" args: "ptr" "word" "word" */
#define OBSD41_SYS_open 5

/* syscall: "close" ret: "word" args: "word" */
#define OBSD41_SYS_close 6

/* syscall: "wait4" ret: "word" args: "word" "ptr" "word" "word" */
#define OBSD41_SYS_wait4 7

/* syscall: "creat_compat43" ret: "word" args: "ptr" "word" */
#define OBSD41_SYS_creat_compat43 8

/* syscall: "link" ret: "word" args: "ptr" "ptr" */
#define OBSD41_SYS_link 9

/* syscall: "unlink" ret: "word" args: "ptr" */
#define OBSD41_SYS_unlink 10

/* syscall: "oexecve" ret: "word" args: "ptr" "ptr" "ptr" */
#define OBSD41_SYS_oexecve 11

/* syscall: "chdir" ret: "word" args: "ptr" */
#define OBSD41_SYS_chdir 12

/* syscall: "fchdir" ret: "word" args: "word" */
#define OBSD41_SYS_fchdir 13

/* syscall: "mknod" ret: "word" args: "ptr" "word" "word" */
#define OBSD41_SYS_mknod 14

/* syscall: "chmod" ret: "word" args: "ptr" "word" */
#define OBSD41_SYS_chmod 15

/* syscall: "chown" ret: "word" args: "ptr" "word" "word" */
#define OBSD41_SYS_chown 16

/* syscall: "brk" ret: "ptr" args: "intptr" */
#define OBSD41_SYS_brk 17

/* syscall: "getfsstat_compat25" ret: "word" args: "ptr" */
#define OBSD41_SYS_getfsstat_compat25 18

/* syscall: "lseek_compat43" ret: "word" args: "word" "word" "word" */
#define OBSD41_SYS_lseek_compat43 19

/* syscall: "getpid" ret: "word" args: */
#define OBSD41_SYS_getpid 20

/* syscall: "mount" ret: "word" args: "ptr" "ptr" "word" "ptr" */
#define OBSD41_SYS_mount 21

/* syscall: "umount" ret: "word" args: "ptr" "word" */
#define OBSD41_SYS_umount 22

/* syscall: "setuid" ret: "word" args: "word" */
#define OBSD41_SYS_setuid 23

/* syscall: "getuid" ret: "word" args: */
#define OBSD41_SYS_getuid 24

/* syscall: "geteuid" ret: "word" args: */
#define OBSD41_SYS_geteuid 25

/* syscall: "ptrace" ret: "word" args: "word" "word" "ptr" "word" */
#define OBSD41_SYS_ptrace 26

/* syscall: "recvmsg" ret: "word" args: "word" "ptr" "word" */
#define OBSD41_SYS_recvmsg 27

/* syscall: "sendmsg" ret: "word" args: "word" "ptr" "word" */
#define OBSD41_SYS_sendmsg 28

/* syscall: "recvfrom" ret: "word" args: "word" "ptr" "word" "word" "ptr" "ptr" */
#define OBSD41_SYS_recvfrom 29

/* syscall: "accept" ret: "word" args: "word" "ptr" "ptr" */
#define OBSD41_SYS_accept 30

/* syscall: "getpeername" ret: "word" args: "word" "ptr" "ptr" */
#define OBSD41_SYS_getpeername 31

/* syscall: "getsockname" ret: "word" args: "word" "ptr" "ptr" */
#define OBSD41_SYS_getsockname 32

/* syscall: "access" ret: "word" args: "ptr" "word" */
#define OBSD41_SYS_access 33

/* syscall: "chflags" ret: "word" args: "ptr" "word" */
#define OBSD41_SYS_chflags 34

/* syscall: "fchflags" ret: "word" args: "word" "word" */
#define OBSD41_SYS_fchflags 35

/* syscall: "sync" ret: "word" args: */
#define OBSD41_SYS_sync 36

/* syscall: "kill" ret: "word" args: "word" "word" */
#define OBSD41_SYS_kill 37

/* syscall: "stat_compat43" ret: "word" args: "ptr" "ptr" */
#define OBSD41_SYS_stat_compat43 38

/* syscall: "getppid" ret: "word" args: */
#define OBSD41_SYS_getppid 39

/* syscall: "lstat_compat43" ret: "word" args: "ptr" "ptr" */
#define OBSD41_SYS_lstat_compat43 40

/* syscall: "dup" ret: "word" args: "word" */
#define OBSD41_SYS_dup 41

/* syscall: "opipe" ret: "word" args: */
#define OBSD41_SYS_opipe 42

/* syscall: "getegid" ret: "word" args: */
#define OBSD41_SYS_getegid 43

/* syscall: "profil" ret: "word" args: "ptr" "word" "word" "word" */
#define OBSD41_SYS_profil 44

/* syscall: "ktrace" ret: "word" args: "ptr" "word" "word" "word" */
#define OBSD41_SYS_ktrace 45

/* syscall: "sigaction" ret: "word" args: "word" "ptr" "ptr" */
#define OBSD41_SYS_sigaction 46

/* syscall: "getgid" ret: "word" args: */
#define OBSD41_SYS_getgid 47

/* syscall: "sigprocmask" ret: "word" args: "word" "word" */
#define OBSD41_SYS_sigprocmask 48

/* syscall: "getlogin" ret: "word" args: "ptr" "word" */
#define OBSD41_SYS_getlogin 49

/* syscall: "setlogin" ret: "word" args: "ptr" */
#define OBSD41_SYS_setlogin 50

/* syscall: "acct" ret: "word" args: "ptr" */
#define OBSD41_SYS_acct 51

/* syscall: "sigpending" ret: "word" args: */
#define OBSD41_SYS_sigpending 52

/* syscall: "osigaltstack" ret: "word" args: "word" "ptr" "ptr" */
#define OBSD41_SYS_osigaltstack 53

/* syscall: "ioctl" ret: "word" args: "word" "intptr" "intptr" */
#define OBSD41_SYS_ioctl 54

/* syscall: "reboot" ret: "word" args: "word" */
#define OBSD41_SYS_reboot 55

/* syscall: "revoke" ret: "word" args: "ptr" */
#define OBSD41_SYS_revoke 56

/* syscall: "symlink" ret: "word" args: "ptr" "ptr" */
#define OBSD41_SYS_symlink 57

/* syscall: "readlink" ret: "word" args: "ptr" "ptr" "word" */
#define OBSD41_SYS_readlink 58

/* syscall: "execve" ret: "word" args: "ptr" "ptr" "ptr" */
#define OBSD41_SYS_execve 59

/* syscall: "umask" ret: "word" args: "word" */
#define OBSD41_SYS_umask 60

/* syscall: "chroot" ret: "word" args: "ptr" */
#define OBSD41_SYS_chroot 61

/* syscall: "fstat_compat43" ret: "word" args: "word" "ptr" */
#define OBSD41_SYS_fstat_compat43 62

/* syscall: "getkerninfo_compat43" ret: "word" args: */
#define OBSD41_SYS_getkerninfo_compat43 63

/* syscall: "getpagesize_compat43" ret: "word" args: */
#define OBSD41_SYS_getpagesize_compat43 64

/* syscall: "msync_compat43" ret: "word" args: */
#define OBSD41_SYS_msync_compat43 65

/* syscall: "vfork" ret: "word" args: */
#define OBSD41_SYS_vfork 66

/* syscall: "ovread" ret: "word" args: "word" "ptr" "word" */
#define OBSD41_SYS_ovread 67

/* syscall: "ovwrite" ret: "word" args: "word" "ptr" "word" */
#define OBSD41_SYS_ovwrite 68

/* syscall: "sbrk" ret: "ptr" args: "word" */
#define OBSD41_SYS_sbrk 69

/* syscall: "sstk" ret: "ptr" args: "word" */
#define OBSD41_SYS_sstk 70

/* syscall: "mmap_compat43" ret: "word" args: */
#define OBSD41_SYS_mmap_compat43 71

/* syscall: "vadvise" ret: "word" args: "word" */
#define OBSD41_SYS_vadvise 72

/* syscall: "munmap" ret: "word" args: "ptr" "word" */
#define OBSD41_SYS_munmap 73

/* syscall: "mprotect" ret: "word" args: "ptr" "word" "word" */
#define OBSD41_SYS_mprotect 74

/* syscall: "madvise" ret: "word" args: "ptr" "word" "word" */
#define OBSD41_SYS_madvise 75

/* syscall: "ovhangup" ret: "word" args: */
#define OBSD41_SYS_ovhangup 76

/* syscall: "ovlimit" ret: "word" args: */
#define OBSD41_SYS_ovlimit 77

/* syscall: "mincore" ret: "word" args: "ptr" "word" "ptr" */
#define OBSD41_SYS_mincore 78

/* syscall: "getgroups" ret: "word" args: "word" "ptr" */
#define OBSD41_SYS_getgroups 79

/* syscall: "setgroups" ret: "word" args: "word" "ptr" */
#define OBSD41_SYS_setgroups 80

/* syscall: "getpgrp" ret: "word" args: */
#define OBSD41_SYS_getpgrp 81

/* syscall: "setpgid" ret: "word" args: "word" "word" */
#define OBSD41_SYS_setpgid 82

/* syscall: "setitimer" ret: "word" args: "word" "ptr" "ptr" */
#define OBSD41_SYS_setitimer 83

/* syscall: "wait_compat43" ret: "word" args: "word" */
#define OBSD41_SYS_wait_compat43 84

/* syscall: "swapon_compat25" ret: "word" args: "ptr" */
#define OBSD41_SYS_swapon_compat25 85

/* syscall: "getitimer" ret: "word" args: "word" "ptr" */
#define OBSD41_SYS_getitimer 86

/* syscall: "gethostname_compat43" ret: "word" args: "ptr" "word" */
#define OBSD41_SYS_gethostname_compat43 87

/* syscall: "sethostname_compat43" ret: "word" args: "ptr" "word" */
#define OBSD41_SYS_sethostname_compat43 88

/* syscall: "getdtablesize_compat43" ret: "word" args: */
#define OBSD41_SYS_getdtablesize_compat43 89

/* syscall: "dup2" ret: "word" args: "word" "word" */
#define OBSD41_SYS_dup2 90

/* syscall: "fcntl" ret: "word" args: "word" "word" "intptr" */
#define OBSD41_SYS_fcntl 92

/* syscall: "select" ret: "word" args: "word" "ptr" "ptr" "ptr" "ptr" */
#define OBSD41_SYS_select 93

/* syscall: "fsync" ret: "word" args: "word" */
#define OBSD41_SYS_fsync 95

/* syscall: "setpriority" ret: "word" args: "word" "word" "word" */
#define OBSD41_SYS_setpriority 96

/* syscall: "socket" ret: "word" args: "word" "word" "word" */
#define OBSD41_SYS_socket 97

/* syscall: "connect" ret: "word" args: "word" "ptr" "word" */
#define OBSD41_SYS_connect 98

/* syscall: "accept_compat43" ret: "word" args: "word" "ptr" "ptr" */
#define OBSD41_SYS_accept_compat43 99

/* syscall: "getpriority" ret: "word" args: "word" "word" */
#define OBSD41_SYS_getpriority 100

/* syscall: "send_compat43" ret: "word" args: "word" "ptr" "word" */
#define OBSD41_SYS_send_compat43 101

/* syscall: "recv_compat43" ret: "word" args: "word" "ptr" "word" */
#define OBSD41_SYS_recv_compat43 102

/* syscall: "sigreturn" ret: "word" args: "word" "ptr" "word" */
#define OBSD41_SYS_sigreturn 103

/* syscall: "bind" ret: "word" args: "word" "ptr" "word" */
#define OBSD41_SYS_bind 104

/* syscall: "setsockopt" ret: "word" args: "word" "word" "word" "ptr" "word" */
#define OBSD41_SYS_setsockopt 105

/* syscall: "listen" ret: "word" args: "word" "word" */
#define OBSD41_SYS_listen 106

/* syscall: "ovtimes" ret: "word" args: */
#define OBSD41_SYS_ovtimes 107

/* syscall: "sigvec_compat43" ret: "word" args: "word" "ptr" "ptr" */
#define OBSD41_SYS_sigvec_compat43 108

/* syscall: "sigblock_compat43" ret: "word" args: "word" */
#define OBSD41_SYS_sigblock_compat43 109

/* syscall: "sigsetmask_compat43" ret: "word" args: "word" */
#define OBSD41_SYS_sigsetmask_compat43 110

/* syscall: "sigsuspend" ret: "word" args: "word" */
#define OBSD41_SYS_sigsuspend 111

/* syscall: "sigstack_compat43" ret: "word" args: */
#define OBSD41_SYS_sigstack_compat43 112

/* syscall: "recvmsg_compat43" ret: "word" args: "word" "ptr" "word" */
#define OBSD41_SYS_recvmsg_compat43 113

/* syscall: "sendmsg_compat43" ret: "word" args: "word" "ptr" "word" */
#define OBSD41_SYS_sendmsg_compat43 114

/* syscall: "ovtrace" ret: "word" args: */
#define OBSD41_SYS_ovtrace 115

/* syscall: "gettimeofday" ret: "word" args: "ptr" "ptr" */
#define OBSD41_SYS_gettimeofday 116

/* syscall: "getrusage" ret: "word" args: "word" "ptr" */
#define OBSD41_SYS_getrusage 117

/* syscall: "getsockopt" ret: "word" args: "word" "word" "word" "ptr" "ptr" */
#define OBSD41_SYS_getsockopt 118

/* syscall: "oresuba" ret: "word" args: */
#define OBSD41_SYS_oresuba 119

/* syscall: "readv" ret: "word" args: "word" "ptr" "word" */
#define OBSD41_SYS_readv 120

/* syscall: "writev" ret: "word" args: "word" "ptr" "word" */
#define OBSD41_SYS_writev 121

/* syscall: "settimeofday" ret: "word" args: "ptr" "ptr" */
#define OBSD41_SYS_settimeofday 122

/* syscall: "fchown" ret: "word" args: "word" "word" "word" */
#define OBSD41_SYS_fchown 123

/* syscall: "fchmod" ret: "word" args: "word" "word" */
#define OBSD41_SYS_fchmod 124

/* syscall: "recvfrom_compat43" ret: "word" args: "word" "ptr" "word" "word" "ptr" "ptr" */
#define OBSD41_SYS_recvfrom_compat43 125

/* syscall: "setreuid" ret: "word" args: "word" "word" */
#define OBSD41_SYS_setreuid 126

/* syscall: "setregid" ret: "word" args: "word" "word" */
#define OBSD41_SYS_setregid 127

/* syscall: "rename" ret: "word" args: "ptr" "ptr" */
#define OBSD41_SYS_rename 128

/* syscall: "truncate_compat43" ret: "word" args: "ptr" "word" */
#define OBSD41_SYS_truncate_compat43 129

/* syscall: "ftruncate_compat43" ret: "word" args: "word" "word" */
#define OBSD41_SYS_ftruncate_compat43 130

/* syscall: "flock" ret: "word" args: "word" "word" */
#define OBSD41_SYS_flock 131

/* syscall: "mkfifo" ret: "word" args: "ptr" "word" */
#define OBSD41_SYS_mkfifo 132

/* syscall: "sendto" ret: "word" args: "word" "ptr" "word" "word" "ptr" "word" */
#define OBSD41_SYS_sendto 133

/* syscall: "shutdown" ret: "word" args: "word" "word" */
#define OBSD41_SYS_shutdown 134

/* syscall: "socketpair" ret: "word" args: "word" "word" "word" "ptr" */
#define OBSD41_SYS_socketpair 135

/* syscall: "mkdir" ret: "word" args: "ptr" "word" */
#define OBSD41_SYS_mkdir 136

/* syscall: "rmdir" ret: "word" args: "ptr" */
#define OBSD41_SYS_rmdir 137

/* syscall: "utimes" ret: "word" args: "ptr" "ptr" */
#define OBSD41_SYS_utimes 138

/* syscall: "sigreturn_compat42" ret: "word" args: "ptr" */
#define OBSD41_SYS_sigreturn_compat42 139

/* syscall: "adjtime" ret: "word" args: "ptr" "ptr" */
#define OBSD41_SYS_adjtime 140

/* syscall: "getpeername_compat43" ret: "word" args: "ptr" "word" */
#define OBSD41_SYS_getpeername_compat43 141

/* syscall: "gethostid_compat43" ret: "word" args: "ptr" "word" */
#define OBSD41_SYS_gethostid_compat43 142

/* syscall: "sethostid_compat43" ret: "word" args: "ptr" */
#define OBSD41_SYS_sethostid_compat43 143

/* syscall: "getrlimit_compat43" ret: "word" args: "word" "ptr" */
#define OBSD41_SYS_getrlimit_compat43 144

/* syscall: "setrlimit_compat43" ret: "word" args: "word" "ptr" */
#define OBSD41_SYS_setrlimit_compat43 145

/* syscall: "killpg_compat43" ret: "word" args: "word" "word" */
#define OBSD41_SYS_killpg_compat43 146

/* syscall: "setsid" ret: "word" args: */
#define OBSD41_SYS_setsid 147

/* syscall: "quotactl" ret: "word" args: "ptr" "word" "word" "ptr" */
#define OBSD41_SYS_quotactl 148

/* syscall: "quota_compat43" ret: "word" args: */
#define OBSD41_SYS_quota_compat43 149

/* syscall: "getsockname_compat43" ret: "word" args: "ptr" "word" */
#define OBSD41_SYS_getsockname_compat43 150

/* syscall: "nfssvc" ret: "word" args: "word" "ptr" */
#define OBSD41_SYS_nfssvc 155

/* syscall: "getdirentries_compat43" ret: "word" args: */
#define OBSD41_SYS_getdirentries_compat43 156

/* syscall: "statfs_compat25" ret: "word" args: */
#define OBSD41_SYS_statfs_compat25 157

/* syscall: "statfs_compat26" ret: "word" args: */
#define OBSD41_SYS_statfs_compat26 158

/* syscall: "getfh" ret: "word" args: "ptr" "ptr" */
#define OBSD41_SYS_getfh 161

/* syscall: "getdomainname_compat09" ret: "word" args: "ptr" "word" */
#define OBSD41_SYS_getdomainname_compat09 162

/* syscall: "setdomainname_compat09" ret: "word" args: "ptr" "word" */
#define OBSD41_SYS_setdomainname_compat09 163

/* syscall: "uname_compat09" ret: "word" args: "ptr" */
#define OBSD41_SYS_uname_compat09 164

/* syscall: "sysarch" ret: "word" args: "word" "ptr" */
#define OBSD41_SYS_sysarch 165

/* syscall: "semsys_compat10" ret: "word" args: */
#define OBSD41_SYS_semsys_compat10 169

/* syscall: "msgsys_compat10" ret: "word" args: */
#define OBSD41_SYS_msgsys_compat10 170

/* syscall: "shmsys_compat10" ret: "word" args: */
#define OBSD41_SYS_shmsys_compat10 171

/* syscall: "pread" ret: "word" args: "word" "ptr" "word" "word" "dword" */
#define OBSD41_SYS_pread 173

/* syscall: "pwrite" ret: "word" args: "word" "ptr" "word" "word" "dword" */
#define OBSD41_SYS_pwrite 174

/* syscall: "setgid" ret: "word" args: "word" */
#define OBSD41_SYS_setgid 181

/* syscall: "setegid" ret: "word" args: "word" */
#define OBSD41_SYS_setegid 182

/* syscall: "seteuid" ret: "word" args: "word" */
#define OBSD41_SYS_seteuid 183

/* syscall: "lfs_bmapv" ret: "word" args: "ptr" "ptr" "word" */
#define OBSD41_SYS_lfs_bmapv 184

/* syscall: "lfs_markv" ret: "word" args: "ptr" "ptr" "word" */
#define OBSD41_SYS_lfs_markv 185

/* syscall: "lfs_segclean" ret: "word" args: "ptr" "intptr" */
#define OBSD41_SYS_lfs_segclean 186

/* syscall: "lfs_segwait" ret: "word" args: "ptr" "ptr" */
#define OBSD41_SYS_lfs_segwait 187

/* syscall: "stat_compat35" ret: "word" args: "word" "ptr" */
#define OBSD41_SYS_stat_compat35 188

/* syscall: "fstat_compat35" ret: "word" args: "word" "ptr" */
#define OBSD41_SYS_fstat_compat35 189

/* syscall: "lstat_compat35" ret: "word" args: "word" "ptr" */
#define OBSD41_SYS_lstat_compat35 190

/* syscall: "pathconf" ret: "intptr" args: "ptr" "word" */
#define OBSD41_SYS_pathconf 191

/* syscall: "fpathconf" ret: "intptr" args: "word" "word" */
#define OBSD41_SYS_fpathconf 192

/* syscall: "swapctl" ret: "word" args: "word" "ptr" "word" */
#define OBSD41_SYS_swapctl 193

/* syscall: "getrlimit" ret: "word" args: "word" "ptr" */
#define OBSD41_SYS_getrlimit 194

/* syscall: "setrlimit" ret: "word" args: "word" "ptr" */
#define OBSD41_SYS_setrlimit 195

/* syscall: "getdirentries" ret: "word" args: "word" "ptr" "word" "ptr" */
#define OBSD41_SYS_getdirentries 196

/* syscall: "mmap" ret: "intptr" args: "intptr" "word" "word" "word" "word" "intptr" "dword" */
#define OBSD41_SYS_mmap 197

/* syscall: "__syscall" ret: "dword" args: "dword" "..." */
#define OBSD41_SYS___syscall 198

/* syscall: "lseek" ret: "dword" args: "word" "word" "dword" "word" */
#define OBSD41_SYS_lseek 199

/* syscall: "truncate" ret: "word" args: "ptr" "dword" */
#define OBSD41_SYS_truncate 200

/* syscall: "ftruncate" ret: "word" args: "word" "dword" */
#define OBSD41_SYS_ftruncate 201

/* syscall: "__sysctl" ret: "word" args: "ptr" "word" "ptr" "ptr" "ptr" "word" */
#define OBSD41_SYS___sysctl 202

/* syscall: "mlock" ret: "word" args: "ptr" "word" */
#define OBSD41_SYS_mlock 203

/* syscall: "munlock" ret: "word" args: "ptr" "word" */
#define OBSD41_SYS_munlock 204

/* syscall: "futimes" ret: "word" args: "word" "ptr" */
#define OBSD41_SYS_futimes 206

/* syscall: "getpgid" ret: "word" args: "word" */
#define OBSD41_SYS_getpgid 207

/* syscall: "xfspioctl" ret: "word" args: "word" "ptr" "word" "ptr" "word" */
#define OBSD41_SYS_xfspioctl 208

/* syscall: "semctl_compat23" ret: "word" args: */
#define OBSD41_SYS_semctl_compat23 220

/* syscall: "semget" ret: "word" args: "word" "word" "word" */
#define OBSD41_SYS_semget 221

/* syscall: "semop_compat35" ret: "word" args: */
#define OBSD41_SYS_semop_compat35 222

/* syscall: "osys_semconfig" ret: "word" args: */
#define OBSD41_SYS_osys_semconfig 223

/* syscall: "msgctl_compat23" ret: "word" args: */
#define OBSD41_SYS_msgctl_compat23 224

/* syscall: "msgget" ret: "word" args: "word" "word" */
#define OBSD41_SYS_msgget 225

/* syscall: "msgsnd" ret: "word" args: "word" "ptr" "word" "word" */
#define OBSD41_SYS_msgsnd 226

/* syscall: "msgrcv" ret: "word" args: "word" "ptr" "word" "intptr" "word" */
#define OBSD41_SYS_msgrcv 227

/* syscall: "shmat" ret: "ptr" args: "word" "ptr" "word" */
#define OBSD41_SYS_shmat 228

/* syscall: "shmctl_compat23" ret: "word" args: */
#define OBSD41_SYS_shmctl_compat23 229

/* syscall: "shmdt" ret: "word" args: "ptr" */
#define OBSD41_SYS_shmdt 230

/* syscall: "shmget_compat35" ret: "word" args: */
#define OBSD41_SYS_shmget_compat35 231

/* syscall: "clock_gettime" ret: "word" args: "word" "ptr" */
#define OBSD41_SYS_clock_gettime 232

/* syscall: "clock_settime" ret: "word" args: "word" "ptr" */
#define OBSD41_SYS_clock_settime 233

/* syscall: "clock_getres" ret: "word" args: "word" "ptr" */
#define OBSD41_SYS_clock_getres 234

/* syscall: "nanosleep" ret: "word" args: "ptr" "ptr" */
#define OBSD41_SYS_nanosleep 240

/* syscall: "minherit" ret: "word" args: "ptr" "word" "word" */
#define OBSD41_SYS_minherit 250

/* syscall: "rfork" ret: "word" args: "word" */
#define OBSD41_SYS_rfork 251

/* syscall: "poll" ret: "word" args: "ptr" "word" "word" */
#define OBSD41_SYS_poll 252

/* syscall: "issetugid" ret: "word" args: */
#define OBSD41_SYS_issetugid 253

/* syscall: "lchown" ret: "word" args: "ptr" "word" "word" */
#define OBSD41_SYS_lchown 254

/* syscall: "getsid" ret: "word" args: "word" */
#define OBSD41_SYS_getsid 255

/* syscall: "msync" ret: "word" args: "ptr" "word" "word" */
#define OBSD41_SYS_msync 256

/* syscall: "semctl_compat35" ret: "word" args: */
#define OBSD41_SYS_semctl_compat35 257

/* syscall: "shmctl_compat35" ret: "word" args: */
#define OBSD41_SYS_shmctl_compat35 258

/* syscall: "msgctl_compat35" ret: "word" args: */
#define OBSD41_SYS_msgctl_compat35 259

/* syscall: "getfsstat" ret: "word" args: "ptr" "word" "word" */
#define OBSD41_SYS_getfsstat 260

/* syscall: "statfs" ret: "word" args: "ptr" "ptr" */
#define OBSD41_SYS_statfs 261

/* syscall: "fstatfs" ret: "word" args: "word" "ptr" */
#define OBSD41_SYS_fstatfs 262

/* syscall: "pipe" ret: "word" args: "ptr" */
#define OBSD41_SYS_pipe 263

/* syscall: "fhopen" ret: "word" args: "ptr" "word" */
#define OBSD41_SYS_fhopen 264

/* syscall: "fhstat_compat35" ret: "word" args: */
#define OBSD41_SYS_fhstat_compat35 265

/* syscall: "fhstatfs" ret: "word" args: "ptr" "ptr" */
#define OBSD41_SYS_fhstatfs 266

/* syscall: "preadv" ret: "word" args: "word" "ptr" "word" "word" "dword" */
#define OBSD41_SYS_preadv 267

/* syscall: "pwritev" ret: "word" args: "word" "ptr" "word" "word" "dword" */
#define OBSD41_SYS_pwritev 268

/* syscall: "kqueue" ret: "word" args: */
#define OBSD41_SYS_kqueue 269

/* syscall: "kevent" ret: "word" args: "word" "ptr" "word" "ptr" "word" "ptr" */
#define OBSD41_SYS_kevent 270

/* syscall: "mlockall" ret: "word" args: "word" */
#define OBSD41_SYS_mlockall 271

/* syscall: "munlockall" ret: "word" args: "word" */
#define OBSD41_SYS_munlockall 272

/* syscall: "getpeereid" ret: "word" args: "word" "ptr" "ptr" */
#define OBSD41_SYS_getpeereid 273

/* syscall: "getresuid" ret: "word" args: "ptr" "ptr" "ptr" */
#define OBSD41_SYS_getresuid 281

/* syscall: "setresuid" ret: "word" args: "word" "word" "word" */
#define OBSD41_SYS_setresuid 282

/* syscall: "getresgid" ret: "word" args: "ptr" "ptr" "ptr" */
#define OBSD41_SYS_getresgid 283

/* syscall: "setresgid" ret: "word" args: "word" "word" "word" */
#define OBSD41_SYS_setresgid 284

/* syscall: "osys_mquery" ret: "word" args: */
#define OBSD41_SYS_osys_mquery 285

/* syscall: "mquery" ret: "ptr" args: "ptr" "word" "word" "word" "intptr" "dword" */
#define OBSD41_SYS_mquery 286

/* syscall: "closefrom" ret: "word" args: "word" */
#define OBSD41_SYS_closefrom 287

/* syscall: "sigaltstack" ret: "word" args: "ptr" "ptr" */
#define OBSD41_SYS_sigaltstack 288

/* syscall: "shmget" ret: "word" args: "word" "word" */
#define OBSD41_SYS_shmget 289

/* syscall: "semop" ret: "word" args: "word" "ptr" "word" */
#define OBSD41_SYS_semop 290

/* syscall: "stat" ret: "word" args: "ptr" "ptr" */
#define OBSD41_SYS_stat 291

/* syscall: "fstat" ret: "word" args: "word" "ptr" */
#define OBSD41_SYS_fstat 292

/* syscall: "lstat" ret: "word" args: "ptr" "ptr" */
#define OBSD41_SYS_lstat 293

/* syscall: "fhstat" ret: "word" args: "ptr" "ptr" */
#define OBSD41_SYS_fhstat 294

/* syscall: "__semctl" ret: "word" args: "word" "word" "word" "ptr" */
#define OBSD41_SYS___semctl 295

/* syscall: "shmctl" ret: "word" args: "word" "word" "ptr" */
#define OBSD41_SYS_shmctl 296

/* syscall: "msgctl" ret: "word" args: "word" "word" "ptr" */
#define OBSD41_SYS_msgctl 297

/* syscall: "sched_yield" ret: "word" args: */
#define OBSD41_SYS_sched_yield 298

/* syscall: "getthrid" ret: "word" args: */
#define OBSD41_SYS_getthrid 299

/* syscall: "thrsleep" ret: "word" args: "ptr" "word" "ptr" */
#define OBSD41_SYS_thrsleep 300

/* syscall: "thrwakeup" ret: "word" args: "ptr" "word" */
#define OBSD41_SYS_thrwakeup 301

/* syscall: "threxit" ret: "word" args: "word" */
#define OBSD41_SYS_threxit 302

/* syscall: "thrsigdivert" ret: "word" args: "word" "word" */
#define OBSD41_SYS_thrsigdivert 303

/* syscall: "__getcwd" ret: "word" args: "ptr" "word" */
#define OBSD41_SYS___getcwd 304

/* syscall: "adjfreq" ret: "word" args: "ptr" "ptr" */
#define OBSD41_SYS_adjfreq 305


#endif  /* !__obsd41_syscalls_h */
