/* This file is automatically generated from `obsd41.sc' with sc2int.
 * !!! DO NOT EDIT !!!
 */

#ifndef __obsd41_args_h
#define __obsd41_args_h

/* OpenBSD 4.1 System Calls Arguments Data Structures */

/* syscall: "syscall" ret: "word" args: "word" "..." */
typedef uint32_t obsd41_syscall_result_t;
typedef struct __obsd41_syscall_args
  {
    uint32_t arg0;
    xec_param_t const *ap;
  } obsd41_syscall_args_t;

/* syscall: "exit" ret: "word" args: "word" */
typedef uint32_t obsd41_exit_result_t;
typedef struct __obsd41_exit_args
  {
    uint32_t arg0;
  } obsd41_exit_args_t;

/* syscall: "fork" ret: "word" args: */
typedef uint32_t obsd41_fork_result_t;
typedef struct __obsd41_fork_args
  {
    int dummy;
  } obsd41_fork_args_t;

/* syscall: "read" ret: "word" args: "word" "ptr" "word" */
typedef uint32_t obsd41_read_result_t;
typedef struct __obsd41_read_args
  {
    uint32_t arg0;
    void * arg1;
    uint32_t arg2;
  } obsd41_read_args_t;

/* syscall: "write" ret: "word" args: "word" "ptr" "word" */
typedef uint32_t obsd41_write_result_t;
typedef struct __obsd41_write_args
  {
    uint32_t arg0;
    void * arg1;
    uint32_t arg2;
  } obsd41_write_args_t;

/* syscall: "open" ret: "word" args: "ptr" "word" "word" */
typedef uint32_t obsd41_open_result_t;
typedef struct __obsd41_open_args
  {
    void * arg0;
    uint32_t arg1;
    uint32_t arg2;
  } obsd41_open_args_t;

/* syscall: "close" ret: "word" args: "word" */
typedef uint32_t obsd41_close_result_t;
typedef struct __obsd41_close_args
  {
    uint32_t arg0;
  } obsd41_close_args_t;

/* syscall: "wait4" ret: "word" args: "word" "ptr" "word" "word" */
typedef uint32_t obsd41_wait4_result_t;
typedef struct __obsd41_wait4_args
  {
    uint32_t arg0;
    void * arg1;
    uint32_t arg2;
    uint32_t arg3;
  } obsd41_wait4_args_t;

/* syscall: "creat_compat43" ret: "word" args: "ptr" "word" */
typedef uint32_t obsd41_creat_compat43_result_t;
typedef struct __obsd41_creat_compat43_args
  {
    void * arg0;
    uint32_t arg1;
  } obsd41_creat_compat43_args_t;

/* syscall: "link" ret: "word" args: "ptr" "ptr" */
typedef uint32_t obsd41_link_result_t;
typedef struct __obsd41_link_args
  {
    void * arg0;
    void * arg1;
  } obsd41_link_args_t;

/* syscall: "unlink" ret: "word" args: "ptr" */
typedef uint32_t obsd41_unlink_result_t;
typedef struct __obsd41_unlink_args
  {
    void * arg0;
  } obsd41_unlink_args_t;

/* syscall: "oexecve" ret: "word" args: "ptr" "ptr" "ptr" */
typedef uint32_t obsd41_oexecve_result_t;
typedef struct __obsd41_oexecve_args
  {
    void * arg0;
    void * arg1;
    void * arg2;
  } obsd41_oexecve_args_t;

/* syscall: "chdir" ret: "word" args: "ptr" */
typedef uint32_t obsd41_chdir_result_t;
typedef struct __obsd41_chdir_args
  {
    void * arg0;
  } obsd41_chdir_args_t;

/* syscall: "fchdir" ret: "word" args: "word" */
typedef uint32_t obsd41_fchdir_result_t;
typedef struct __obsd41_fchdir_args
  {
    uint32_t arg0;
  } obsd41_fchdir_args_t;

/* syscall: "mknod" ret: "word" args: "ptr" "word" "word" */
typedef uint32_t obsd41_mknod_result_t;
typedef struct __obsd41_mknod_args
  {
    void * arg0;
    uint32_t arg1;
    uint32_t arg2;
  } obsd41_mknod_args_t;

/* syscall: "chmod" ret: "word" args: "ptr" "word" */
typedef uint32_t obsd41_chmod_result_t;
typedef struct __obsd41_chmod_args
  {
    void * arg0;
    uint32_t arg1;
  } obsd41_chmod_args_t;

/* syscall: "chown" ret: "word" args: "ptr" "word" "word" */
typedef uint32_t obsd41_chown_result_t;
typedef struct __obsd41_chown_args
  {
    void * arg0;
    uint32_t arg1;
    uint32_t arg2;
  } obsd41_chown_args_t;

/* syscall: "brk" ret: "ptr" args: "intptr" */
typedef void * obsd41_brk_result_t;
typedef struct __obsd41_brk_args
  {
    uint32_t arg0;
  } obsd41_brk_args_t;

/* syscall: "getfsstat_compat25" ret: "word" args: "ptr" */
typedef uint32_t obsd41_getfsstat_compat25_result_t;
typedef struct __obsd41_getfsstat_compat25_args
  {
    void * arg0;
  } obsd41_getfsstat_compat25_args_t;

/* syscall: "lseek_compat43" ret: "word" args: "word" "word" "word" */
typedef uint32_t obsd41_lseek_compat43_result_t;
typedef struct __obsd41_lseek_compat43_args
  {
    uint32_t arg0;
    uint32_t arg1;
    uint32_t arg2;
  } obsd41_lseek_compat43_args_t;

/* syscall: "getpid" ret: "word" args: */
typedef uint32_t obsd41_getpid_result_t;
typedef struct __obsd41_getpid_args
  {
    int dummy;
  } obsd41_getpid_args_t;

/* syscall: "mount" ret: "word" args: "ptr" "ptr" "word" "ptr" */
typedef uint32_t obsd41_mount_result_t;
typedef struct __obsd41_mount_args
  {
    void * arg0;
    void * arg1;
    uint32_t arg2;
    void * arg3;
  } obsd41_mount_args_t;

/* syscall: "umount" ret: "word" args: "ptr" "word" */
typedef uint32_t obsd41_umount_result_t;
typedef struct __obsd41_umount_args
  {
    void * arg0;
    uint32_t arg1;
  } obsd41_umount_args_t;

/* syscall: "setuid" ret: "word" args: "word" */
typedef uint32_t obsd41_setuid_result_t;
typedef struct __obsd41_setuid_args
  {
    uint32_t arg0;
  } obsd41_setuid_args_t;

/* syscall: "getuid" ret: "word" args: */
typedef uint32_t obsd41_getuid_result_t;
typedef struct __obsd41_getuid_args
  {
    int dummy;
  } obsd41_getuid_args_t;

/* syscall: "geteuid" ret: "word" args: */
typedef uint32_t obsd41_geteuid_result_t;
typedef struct __obsd41_geteuid_args
  {
    int dummy;
  } obsd41_geteuid_args_t;

/* syscall: "ptrace" ret: "word" args: "word" "word" "ptr" "word" */
typedef uint32_t obsd41_ptrace_result_t;
typedef struct __obsd41_ptrace_args
  {
    uint32_t arg0;
    uint32_t arg1;
    void * arg2;
    uint32_t arg3;
  } obsd41_ptrace_args_t;

/* syscall: "recvmsg" ret: "word" args: "word" "ptr" "word" */
typedef uint32_t obsd41_recvmsg_result_t;
typedef struct __obsd41_recvmsg_args
  {
    uint32_t arg0;
    void * arg1;
    uint32_t arg2;
  } obsd41_recvmsg_args_t;

/* syscall: "sendmsg" ret: "word" args: "word" "ptr" "word" */
typedef uint32_t obsd41_sendmsg_result_t;
typedef struct __obsd41_sendmsg_args
  {
    uint32_t arg0;
    void * arg1;
    uint32_t arg2;
  } obsd41_sendmsg_args_t;

/* syscall: "recvfrom" ret: "word" args: "word" "ptr" "word" "word" "ptr" "ptr" */
typedef uint32_t obsd41_recvfrom_result_t;
typedef struct __obsd41_recvfrom_args
  {
    uint32_t arg0;
    void * arg1;
    uint32_t arg2;
    uint32_t arg3;
    void * arg4;
    void * arg5;
  } obsd41_recvfrom_args_t;

/* syscall: "accept" ret: "word" args: "word" "ptr" "ptr" */
typedef uint32_t obsd41_accept_result_t;
typedef struct __obsd41_accept_args
  {
    uint32_t arg0;
    void * arg1;
    void * arg2;
  } obsd41_accept_args_t;

/* syscall: "getpeername" ret: "word" args: "word" "ptr" "ptr" */
typedef uint32_t obsd41_getpeername_result_t;
typedef struct __obsd41_getpeername_args
  {
    uint32_t arg0;
    void * arg1;
    void * arg2;
  } obsd41_getpeername_args_t;

/* syscall: "getsockname" ret: "word" args: "word" "ptr" "ptr" */
typedef uint32_t obsd41_getsockname_result_t;
typedef struct __obsd41_getsockname_args
  {
    uint32_t arg0;
    void * arg1;
    void * arg2;
  } obsd41_getsockname_args_t;

/* syscall: "access" ret: "word" args: "ptr" "word" */
typedef uint32_t obsd41_access_result_t;
typedef struct __obsd41_access_args
  {
    void * arg0;
    uint32_t arg1;
  } obsd41_access_args_t;

/* syscall: "chflags" ret: "word" args: "ptr" "word" */
typedef uint32_t obsd41_chflags_result_t;
typedef struct __obsd41_chflags_args
  {
    void * arg0;
    uint32_t arg1;
  } obsd41_chflags_args_t;

/* syscall: "fchflags" ret: "word" args: "word" "word" */
typedef uint32_t obsd41_fchflags_result_t;
typedef struct __obsd41_fchflags_args
  {
    uint32_t arg0;
    uint32_t arg1;
  } obsd41_fchflags_args_t;

/* syscall: "sync" ret: "word" args: */
typedef uint32_t obsd41_sync_result_t;
typedef struct __obsd41_sync_args
  {
    int dummy;
  } obsd41_sync_args_t;

/* syscall: "kill" ret: "word" args: "word" "word" */
typedef uint32_t obsd41_kill_result_t;
typedef struct __obsd41_kill_args
  {
    uint32_t arg0;
    uint32_t arg1;
  } obsd41_kill_args_t;

/* syscall: "stat_compat43" ret: "word" args: "ptr" "ptr" */
typedef uint32_t obsd41_stat_compat43_result_t;
typedef struct __obsd41_stat_compat43_args
  {
    void * arg0;
    void * arg1;
  } obsd41_stat_compat43_args_t;

/* syscall: "getppid" ret: "word" args: */
typedef uint32_t obsd41_getppid_result_t;
typedef struct __obsd41_getppid_args
  {
    int dummy;
  } obsd41_getppid_args_t;

/* syscall: "lstat_compat43" ret: "word" args: "ptr" "ptr" */
typedef uint32_t obsd41_lstat_compat43_result_t;
typedef struct __obsd41_lstat_compat43_args
  {
    void * arg0;
    void * arg1;
  } obsd41_lstat_compat43_args_t;

/* syscall: "dup" ret: "word" args: "word" */
typedef uint32_t obsd41_dup_result_t;
typedef struct __obsd41_dup_args
  {
    uint32_t arg0;
  } obsd41_dup_args_t;

/* syscall: "opipe" ret: "word" args: */
typedef uint32_t obsd41_opipe_result_t;
typedef struct __obsd41_opipe_args
  {
    int dummy;
  } obsd41_opipe_args_t;

/* syscall: "getegid" ret: "word" args: */
typedef uint32_t obsd41_getegid_result_t;
typedef struct __obsd41_getegid_args
  {
    int dummy;
  } obsd41_getegid_args_t;

/* syscall: "profil" ret: "word" args: "ptr" "word" "word" "word" */
typedef uint32_t obsd41_profil_result_t;
typedef struct __obsd41_profil_args
  {
    void * arg0;
    uint32_t arg1;
    uint32_t arg2;
    uint32_t arg3;
  } obsd41_profil_args_t;

/* syscall: "ktrace" ret: "word" args: "ptr" "word" "word" "word" */
typedef uint32_t obsd41_ktrace_result_t;
typedef struct __obsd41_ktrace_args
  {
    void * arg0;
    uint32_t arg1;
    uint32_t arg2;
    uint32_t arg3;
  } obsd41_ktrace_args_t;

/* syscall: "sigaction" ret: "word" args: "word" "ptr" "ptr" */
typedef uint32_t obsd41_sigaction_result_t;
typedef struct __obsd41_sigaction_args
  {
    uint32_t arg0;
    void * arg1;
    void * arg2;
  } obsd41_sigaction_args_t;

/* syscall: "getgid" ret: "word" args: */
typedef uint32_t obsd41_getgid_result_t;
typedef struct __obsd41_getgid_args
  {
    int dummy;
  } obsd41_getgid_args_t;

/* syscall: "sigprocmask" ret: "word" args: "word" "word" */
typedef uint32_t obsd41_sigprocmask_result_t;
typedef struct __obsd41_sigprocmask_args
  {
    uint32_t arg0;
    uint32_t arg1;
  } obsd41_sigprocmask_args_t;

/* syscall: "getlogin" ret: "word" args: "ptr" "word" */
typedef uint32_t obsd41_getlogin_result_t;
typedef struct __obsd41_getlogin_args
  {
    void * arg0;
    uint32_t arg1;
  } obsd41_getlogin_args_t;

/* syscall: "setlogin" ret: "word" args: "ptr" */
typedef uint32_t obsd41_setlogin_result_t;
typedef struct __obsd41_setlogin_args
  {
    void * arg0;
  } obsd41_setlogin_args_t;

/* syscall: "acct" ret: "word" args: "ptr" */
typedef uint32_t obsd41_acct_result_t;
typedef struct __obsd41_acct_args
  {
    void * arg0;
  } obsd41_acct_args_t;

/* syscall: "sigpending" ret: "word" args: */
typedef uint32_t obsd41_sigpending_result_t;
typedef struct __obsd41_sigpending_args
  {
    int dummy;
  } obsd41_sigpending_args_t;

/* syscall: "osigaltstack" ret: "word" args: "word" "ptr" "ptr" */
typedef uint32_t obsd41_osigaltstack_result_t;
typedef struct __obsd41_osigaltstack_args
  {
    uint32_t arg0;
    void * arg1;
    void * arg2;
  } obsd41_osigaltstack_args_t;

/* syscall: "ioctl" ret: "word" args: "word" "intptr" "intptr" */
typedef uint32_t obsd41_ioctl_result_t;
typedef struct __obsd41_ioctl_args
  {
    uint32_t arg0;
    uint32_t arg1;
    uint32_t arg2;
  } obsd41_ioctl_args_t;

/* syscall: "reboot" ret: "word" args: "word" */
typedef uint32_t obsd41_reboot_result_t;
typedef struct __obsd41_reboot_args
  {
    uint32_t arg0;
  } obsd41_reboot_args_t;

/* syscall: "revoke" ret: "word" args: "ptr" */
typedef uint32_t obsd41_revoke_result_t;
typedef struct __obsd41_revoke_args
  {
    void * arg0;
  } obsd41_revoke_args_t;

/* syscall: "symlink" ret: "word" args: "ptr" "ptr" */
typedef uint32_t obsd41_symlink_result_t;
typedef struct __obsd41_symlink_args
  {
    void * arg0;
    void * arg1;
  } obsd41_symlink_args_t;

/* syscall: "readlink" ret: "word" args: "ptr" "ptr" "word" */
typedef uint32_t obsd41_readlink_result_t;
typedef struct __obsd41_readlink_args
  {
    void * arg0;
    void * arg1;
    uint32_t arg2;
  } obsd41_readlink_args_t;

/* syscall: "execve" ret: "word" args: "ptr" "ptr" "ptr" */
typedef uint32_t obsd41_execve_result_t;
typedef struct __obsd41_execve_args
  {
    void * arg0;
    void * arg1;
    void * arg2;
  } obsd41_execve_args_t;

/* syscall: "umask" ret: "word" args: "word" */
typedef uint32_t obsd41_umask_result_t;
typedef struct __obsd41_umask_args
  {
    uint32_t arg0;
  } obsd41_umask_args_t;

/* syscall: "chroot" ret: "word" args: "ptr" */
typedef uint32_t obsd41_chroot_result_t;
typedef struct __obsd41_chroot_args
  {
    void * arg0;
  } obsd41_chroot_args_t;

/* syscall: "fstat_compat43" ret: "word" args: "word" "ptr" */
typedef uint32_t obsd41_fstat_compat43_result_t;
typedef struct __obsd41_fstat_compat43_args
  {
    uint32_t arg0;
    void * arg1;
  } obsd41_fstat_compat43_args_t;

/* syscall: "getkerninfo_compat43" ret: "word" args: */
typedef uint32_t obsd41_getkerninfo_compat43_result_t;
typedef struct __obsd41_getkerninfo_compat43_args
  {
    int dummy;
  } obsd41_getkerninfo_compat43_args_t;

/* syscall: "getpagesize_compat43" ret: "word" args: */
typedef uint32_t obsd41_getpagesize_compat43_result_t;
typedef struct __obsd41_getpagesize_compat43_args
  {
    int dummy;
  } obsd41_getpagesize_compat43_args_t;

/* syscall: "msync_compat43" ret: "word" args: */
typedef uint32_t obsd41_msync_compat43_result_t;
typedef struct __obsd41_msync_compat43_args
  {
    int dummy;
  } obsd41_msync_compat43_args_t;

/* syscall: "vfork" ret: "word" args: */
typedef uint32_t obsd41_vfork_result_t;
typedef struct __obsd41_vfork_args
  {
    int dummy;
  } obsd41_vfork_args_t;

/* syscall: "ovread" ret: "word" args: "word" "ptr" "word" */
typedef uint32_t obsd41_ovread_result_t;
typedef struct __obsd41_ovread_args
  {
    uint32_t arg0;
    void * arg1;
    uint32_t arg2;
  } obsd41_ovread_args_t;

/* syscall: "ovwrite" ret: "word" args: "word" "ptr" "word" */
typedef uint32_t obsd41_ovwrite_result_t;
typedef struct __obsd41_ovwrite_args
  {
    uint32_t arg0;
    void * arg1;
    uint32_t arg2;
  } obsd41_ovwrite_args_t;

/* syscall: "sbrk" ret: "ptr" args: "word" */
typedef void * obsd41_sbrk_result_t;
typedef struct __obsd41_sbrk_args
  {
    uint32_t arg0;
  } obsd41_sbrk_args_t;

/* syscall: "sstk" ret: "ptr" args: "word" */
typedef void * obsd41_sstk_result_t;
typedef struct __obsd41_sstk_args
  {
    uint32_t arg0;
  } obsd41_sstk_args_t;

/* syscall: "mmap_compat43" ret: "word" args: */
typedef uint32_t obsd41_mmap_compat43_result_t;
typedef struct __obsd41_mmap_compat43_args
  {
    int dummy;
  } obsd41_mmap_compat43_args_t;

/* syscall: "vadvise" ret: "word" args: "word" */
typedef uint32_t obsd41_vadvise_result_t;
typedef struct __obsd41_vadvise_args
  {
    uint32_t arg0;
  } obsd41_vadvise_args_t;

/* syscall: "munmap" ret: "word" args: "ptr" "word" */
typedef uint32_t obsd41_munmap_result_t;
typedef struct __obsd41_munmap_args
  {
    void * arg0;
    uint32_t arg1;
  } obsd41_munmap_args_t;

/* syscall: "mprotect" ret: "word" args: "ptr" "word" "word" */
typedef uint32_t obsd41_mprotect_result_t;
typedef struct __obsd41_mprotect_args
  {
    void * arg0;
    uint32_t arg1;
    uint32_t arg2;
  } obsd41_mprotect_args_t;

/* syscall: "madvise" ret: "word" args: "ptr" "word" "word" */
typedef uint32_t obsd41_madvise_result_t;
typedef struct __obsd41_madvise_args
  {
    void * arg0;
    uint32_t arg1;
    uint32_t arg2;
  } obsd41_madvise_args_t;

/* syscall: "ovhangup" ret: "word" args: */
typedef uint32_t obsd41_ovhangup_result_t;
typedef struct __obsd41_ovhangup_args
  {
    int dummy;
  } obsd41_ovhangup_args_t;

/* syscall: "ovlimit" ret: "word" args: */
typedef uint32_t obsd41_ovlimit_result_t;
typedef struct __obsd41_ovlimit_args
  {
    int dummy;
  } obsd41_ovlimit_args_t;

/* syscall: "mincore" ret: "word" args: "ptr" "word" "ptr" */
typedef uint32_t obsd41_mincore_result_t;
typedef struct __obsd41_mincore_args
  {
    void * arg0;
    uint32_t arg1;
    void * arg2;
  } obsd41_mincore_args_t;

/* syscall: "getgroups" ret: "word" args: "word" "ptr" */
typedef uint32_t obsd41_getgroups_result_t;
typedef struct __obsd41_getgroups_args
  {
    uint32_t arg0;
    void * arg1;
  } obsd41_getgroups_args_t;

/* syscall: "setgroups" ret: "word" args: "word" "ptr" */
typedef uint32_t obsd41_setgroups_result_t;
typedef struct __obsd41_setgroups_args
  {
    uint32_t arg0;
    void * arg1;
  } obsd41_setgroups_args_t;

/* syscall: "getpgrp" ret: "word" args: */
typedef uint32_t obsd41_getpgrp_result_t;
typedef struct __obsd41_getpgrp_args
  {
    int dummy;
  } obsd41_getpgrp_args_t;

/* syscall: "setpgid" ret: "word" args: "word" "word" */
typedef uint32_t obsd41_setpgid_result_t;
typedef struct __obsd41_setpgid_args
  {
    uint32_t arg0;
    uint32_t arg1;
  } obsd41_setpgid_args_t;

/* syscall: "setitimer" ret: "word" args: "word" "ptr" "ptr" */
typedef uint32_t obsd41_setitimer_result_t;
typedef struct __obsd41_setitimer_args
  {
    uint32_t arg0;
    void * arg1;
    void * arg2;
  } obsd41_setitimer_args_t;

/* syscall: "wait_compat43" ret: "word" args: "word" */
typedef uint32_t obsd41_wait_compat43_result_t;
typedef struct __obsd41_wait_compat43_args
  {
    uint32_t arg0;
  } obsd41_wait_compat43_args_t;

/* syscall: "swapon_compat25" ret: "word" args: "ptr" */
typedef uint32_t obsd41_swapon_compat25_result_t;
typedef struct __obsd41_swapon_compat25_args
  {
    void * arg0;
  } obsd41_swapon_compat25_args_t;

/* syscall: "getitimer" ret: "word" args: "word" "ptr" */
typedef uint32_t obsd41_getitimer_result_t;
typedef struct __obsd41_getitimer_args
  {
    uint32_t arg0;
    void * arg1;
  } obsd41_getitimer_args_t;

/* syscall: "gethostname_compat43" ret: "word" args: "ptr" "word" */
typedef uint32_t obsd41_gethostname_compat43_result_t;
typedef struct __obsd41_gethostname_compat43_args
  {
    void * arg0;
    uint32_t arg1;
  } obsd41_gethostname_compat43_args_t;

/* syscall: "sethostname_compat43" ret: "word" args: "ptr" "word" */
typedef uint32_t obsd41_sethostname_compat43_result_t;
typedef struct __obsd41_sethostname_compat43_args
  {
    void * arg0;
    uint32_t arg1;
  } obsd41_sethostname_compat43_args_t;

/* syscall: "getdtablesize_compat43" ret: "word" args: */
typedef uint32_t obsd41_getdtablesize_compat43_result_t;
typedef struct __obsd41_getdtablesize_compat43_args
  {
    int dummy;
  } obsd41_getdtablesize_compat43_args_t;

/* syscall: "dup2" ret: "word" args: "word" "word" */
typedef uint32_t obsd41_dup2_result_t;
typedef struct __obsd41_dup2_args
  {
    uint32_t arg0;
    uint32_t arg1;
  } obsd41_dup2_args_t;

/* syscall: "fcntl" ret: "word" args: "word" "word" "intptr" */
typedef uint32_t obsd41_fcntl_result_t;
typedef struct __obsd41_fcntl_args
  {
    uint32_t arg0;
    uint32_t arg1;
    uint32_t arg2;
  } obsd41_fcntl_args_t;

/* syscall: "select" ret: "word" args: "word" "ptr" "ptr" "ptr" "ptr" */
typedef uint32_t obsd41_select_result_t;
typedef struct __obsd41_select_args
  {
    uint32_t arg0;
    void * arg1;
    void * arg2;
    void * arg3;
    void * arg4;
  } obsd41_select_args_t;

/* syscall: "fsync" ret: "word" args: "word" */
typedef uint32_t obsd41_fsync_result_t;
typedef struct __obsd41_fsync_args
  {
    uint32_t arg0;
  } obsd41_fsync_args_t;

/* syscall: "setpriority" ret: "word" args: "word" "word" "word" */
typedef uint32_t obsd41_setpriority_result_t;
typedef struct __obsd41_setpriority_args
  {
    uint32_t arg0;
    uint32_t arg1;
    uint32_t arg2;
  } obsd41_setpriority_args_t;

/* syscall: "socket" ret: "word" args: "word" "word" "word" */
typedef uint32_t obsd41_socket_result_t;
typedef struct __obsd41_socket_args
  {
    uint32_t arg0;
    uint32_t arg1;
    uint32_t arg2;
  } obsd41_socket_args_t;

/* syscall: "connect" ret: "word" args: "word" "ptr" "word" */
typedef uint32_t obsd41_connect_result_t;
typedef struct __obsd41_connect_args
  {
    uint32_t arg0;
    void * arg1;
    uint32_t arg2;
  } obsd41_connect_args_t;

/* syscall: "accept_compat43" ret: "word" args: "word" "ptr" "ptr" */
typedef uint32_t obsd41_accept_compat43_result_t;
typedef struct __obsd41_accept_compat43_args
  {
    uint32_t arg0;
    void * arg1;
    void * arg2;
  } obsd41_accept_compat43_args_t;

/* syscall: "getpriority" ret: "word" args: "word" "word" */
typedef uint32_t obsd41_getpriority_result_t;
typedef struct __obsd41_getpriority_args
  {
    uint32_t arg0;
    uint32_t arg1;
  } obsd41_getpriority_args_t;

/* syscall: "send_compat43" ret: "word" args: "word" "ptr" "word" */
typedef uint32_t obsd41_send_compat43_result_t;
typedef struct __obsd41_send_compat43_args
  {
    uint32_t arg0;
    void * arg1;
    uint32_t arg2;
  } obsd41_send_compat43_args_t;

/* syscall: "recv_compat43" ret: "word" args: "word" "ptr" "word" */
typedef uint32_t obsd41_recv_compat43_result_t;
typedef struct __obsd41_recv_compat43_args
  {
    uint32_t arg0;
    void * arg1;
    uint32_t arg2;
  } obsd41_recv_compat43_args_t;

/* syscall: "sigreturn" ret: "word" args: "word" "ptr" "word" */
typedef uint32_t obsd41_sigreturn_result_t;
typedef struct __obsd41_sigreturn_args
  {
    uint32_t arg0;
    void * arg1;
    uint32_t arg2;
  } obsd41_sigreturn_args_t;

/* syscall: "bind" ret: "word" args: "word" "ptr" "word" */
typedef uint32_t obsd41_bind_result_t;
typedef struct __obsd41_bind_args
  {
    uint32_t arg0;
    void * arg1;
    uint32_t arg2;
  } obsd41_bind_args_t;

/* syscall: "setsockopt" ret: "word" args: "word" "word" "word" "ptr" "word" */
typedef uint32_t obsd41_setsockopt_result_t;
typedef struct __obsd41_setsockopt_args
  {
    uint32_t arg0;
    uint32_t arg1;
    uint32_t arg2;
    void * arg3;
    uint32_t arg4;
  } obsd41_setsockopt_args_t;

/* syscall: "listen" ret: "word" args: "word" "word" */
typedef uint32_t obsd41_listen_result_t;
typedef struct __obsd41_listen_args
  {
    uint32_t arg0;
    uint32_t arg1;
  } obsd41_listen_args_t;

/* syscall: "ovtimes" ret: "word" args: */
typedef uint32_t obsd41_ovtimes_result_t;
typedef struct __obsd41_ovtimes_args
  {
    int dummy;
  } obsd41_ovtimes_args_t;

/* syscall: "sigvec_compat43" ret: "word" args: "word" "ptr" "ptr" */
typedef uint32_t obsd41_sigvec_compat43_result_t;
typedef struct __obsd41_sigvec_compat43_args
  {
    uint32_t arg0;
    void * arg1;
    void * arg2;
  } obsd41_sigvec_compat43_args_t;

/* syscall: "sigblock_compat43" ret: "word" args: "word" */
typedef uint32_t obsd41_sigblock_compat43_result_t;
typedef struct __obsd41_sigblock_compat43_args
  {
    uint32_t arg0;
  } obsd41_sigblock_compat43_args_t;

/* syscall: "sigsetmask_compat43" ret: "word" args: "word" */
typedef uint32_t obsd41_sigsetmask_compat43_result_t;
typedef struct __obsd41_sigsetmask_compat43_args
  {
    uint32_t arg0;
  } obsd41_sigsetmask_compat43_args_t;

/* syscall: "sigsuspend" ret: "word" args: "word" */
typedef uint32_t obsd41_sigsuspend_result_t;
typedef struct __obsd41_sigsuspend_args
  {
    uint32_t arg0;
  } obsd41_sigsuspend_args_t;

/* syscall: "sigstack_compat43" ret: "word" args: */
typedef uint32_t obsd41_sigstack_compat43_result_t;
typedef struct __obsd41_sigstack_compat43_args
  {
    int dummy;
  } obsd41_sigstack_compat43_args_t;

/* syscall: "recvmsg_compat43" ret: "word" args: "word" "ptr" "word" */
typedef uint32_t obsd41_recvmsg_compat43_result_t;
typedef struct __obsd41_recvmsg_compat43_args
  {
    uint32_t arg0;
    void * arg1;
    uint32_t arg2;
  } obsd41_recvmsg_compat43_args_t;

/* syscall: "sendmsg_compat43" ret: "word" args: "word" "ptr" "word" */
typedef uint32_t obsd41_sendmsg_compat43_result_t;
typedef struct __obsd41_sendmsg_compat43_args
  {
    uint32_t arg0;
    void * arg1;
    uint32_t arg2;
  } obsd41_sendmsg_compat43_args_t;

/* syscall: "ovtrace" ret: "word" args: */
typedef uint32_t obsd41_ovtrace_result_t;
typedef struct __obsd41_ovtrace_args
  {
    int dummy;
  } obsd41_ovtrace_args_t;

/* syscall: "gettimeofday" ret: "word" args: "ptr" "ptr" */
typedef uint32_t obsd41_gettimeofday_result_t;
typedef struct __obsd41_gettimeofday_args
  {
    void * arg0;
    void * arg1;
  } obsd41_gettimeofday_args_t;

/* syscall: "getrusage" ret: "word" args: "word" "ptr" */
typedef uint32_t obsd41_getrusage_result_t;
typedef struct __obsd41_getrusage_args
  {
    uint32_t arg0;
    void * arg1;
  } obsd41_getrusage_args_t;

/* syscall: "getsockopt" ret: "word" args: "word" "word" "word" "ptr" "ptr" */
typedef uint32_t obsd41_getsockopt_result_t;
typedef struct __obsd41_getsockopt_args
  {
    uint32_t arg0;
    uint32_t arg1;
    uint32_t arg2;
    void * arg3;
    void * arg4;
  } obsd41_getsockopt_args_t;

/* syscall: "oresuba" ret: "word" args: */
typedef uint32_t obsd41_oresuba_result_t;
typedef struct __obsd41_oresuba_args
  {
    int dummy;
  } obsd41_oresuba_args_t;

/* syscall: "readv" ret: "word" args: "word" "ptr" "word" */
typedef uint32_t obsd41_readv_result_t;
typedef struct __obsd41_readv_args
  {
    uint32_t arg0;
    void * arg1;
    uint32_t arg2;
  } obsd41_readv_args_t;

/* syscall: "writev" ret: "word" args: "word" "ptr" "word" */
typedef uint32_t obsd41_writev_result_t;
typedef struct __obsd41_writev_args
  {
    uint32_t arg0;
    void * arg1;
    uint32_t arg2;
  } obsd41_writev_args_t;

/* syscall: "settimeofday" ret: "word" args: "ptr" "ptr" */
typedef uint32_t obsd41_settimeofday_result_t;
typedef struct __obsd41_settimeofday_args
  {
    void * arg0;
    void * arg1;
  } obsd41_settimeofday_args_t;

/* syscall: "fchown" ret: "word" args: "word" "word" "word" */
typedef uint32_t obsd41_fchown_result_t;
typedef struct __obsd41_fchown_args
  {
    uint32_t arg0;
    uint32_t arg1;
    uint32_t arg2;
  } obsd41_fchown_args_t;

/* syscall: "fchmod" ret: "word" args: "word" "word" */
typedef uint32_t obsd41_fchmod_result_t;
typedef struct __obsd41_fchmod_args
  {
    uint32_t arg0;
    uint32_t arg1;
  } obsd41_fchmod_args_t;

/* syscall: "recvfrom_compat43" ret: "word" args: "word" "ptr" "word" "word" "ptr" "ptr" */
typedef uint32_t obsd41_recvfrom_compat43_result_t;
typedef struct __obsd41_recvfrom_compat43_args
  {
    uint32_t arg0;
    void * arg1;
    uint32_t arg2;
    uint32_t arg3;
    void * arg4;
    void * arg5;
  } obsd41_recvfrom_compat43_args_t;

/* syscall: "setreuid" ret: "word" args: "word" "word" */
typedef uint32_t obsd41_setreuid_result_t;
typedef struct __obsd41_setreuid_args
  {
    uint32_t arg0;
    uint32_t arg1;
  } obsd41_setreuid_args_t;

/* syscall: "setregid" ret: "word" args: "word" "word" */
typedef uint32_t obsd41_setregid_result_t;
typedef struct __obsd41_setregid_args
  {
    uint32_t arg0;
    uint32_t arg1;
  } obsd41_setregid_args_t;

/* syscall: "rename" ret: "word" args: "ptr" "ptr" */
typedef uint32_t obsd41_rename_result_t;
typedef struct __obsd41_rename_args
  {
    void * arg0;
    void * arg1;
  } obsd41_rename_args_t;

/* syscall: "truncate_compat43" ret: "word" args: "ptr" "word" */
typedef uint32_t obsd41_truncate_compat43_result_t;
typedef struct __obsd41_truncate_compat43_args
  {
    void * arg0;
    uint32_t arg1;
  } obsd41_truncate_compat43_args_t;

/* syscall: "ftruncate_compat43" ret: "word" args: "word" "word" */
typedef uint32_t obsd41_ftruncate_compat43_result_t;
typedef struct __obsd41_ftruncate_compat43_args
  {
    uint32_t arg0;
    uint32_t arg1;
  } obsd41_ftruncate_compat43_args_t;

/* syscall: "flock" ret: "word" args: "word" "word" */
typedef uint32_t obsd41_flock_result_t;
typedef struct __obsd41_flock_args
  {
    uint32_t arg0;
    uint32_t arg1;
  } obsd41_flock_args_t;

/* syscall: "mkfifo" ret: "word" args: "ptr" "word" */
typedef uint32_t obsd41_mkfifo_result_t;
typedef struct __obsd41_mkfifo_args
  {
    void * arg0;
    uint32_t arg1;
  } obsd41_mkfifo_args_t;

/* syscall: "sendto" ret: "word" args: "word" "ptr" "word" "word" "ptr" "word" */
typedef uint32_t obsd41_sendto_result_t;
typedef struct __obsd41_sendto_args
  {
    uint32_t arg0;
    void * arg1;
    uint32_t arg2;
    uint32_t arg3;
    void * arg4;
    uint32_t arg5;
  } obsd41_sendto_args_t;

/* syscall: "shutdown" ret: "word" args: "word" "word" */
typedef uint32_t obsd41_shutdown_result_t;
typedef struct __obsd41_shutdown_args
  {
    uint32_t arg0;
    uint32_t arg1;
  } obsd41_shutdown_args_t;

/* syscall: "socketpair" ret: "word" args: "word" "word" "word" "ptr" */
typedef uint32_t obsd41_socketpair_result_t;
typedef struct __obsd41_socketpair_args
  {
    uint32_t arg0;
    uint32_t arg1;
    uint32_t arg2;
    void * arg3;
  } obsd41_socketpair_args_t;

/* syscall: "mkdir" ret: "word" args: "ptr" "word" */
typedef uint32_t obsd41_mkdir_result_t;
typedef struct __obsd41_mkdir_args
  {
    void * arg0;
    uint32_t arg1;
  } obsd41_mkdir_args_t;

/* syscall: "rmdir" ret: "word" args: "ptr" */
typedef uint32_t obsd41_rmdir_result_t;
typedef struct __obsd41_rmdir_args
  {
    void * arg0;
  } obsd41_rmdir_args_t;

/* syscall: "utimes" ret: "word" args: "ptr" "ptr" */
typedef uint32_t obsd41_utimes_result_t;
typedef struct __obsd41_utimes_args
  {
    void * arg0;
    void * arg1;
  } obsd41_utimes_args_t;

/* syscall: "sigreturn_compat42" ret: "word" args: "ptr" */
typedef uint32_t obsd41_sigreturn_compat42_result_t;
typedef struct __obsd41_sigreturn_compat42_args
  {
    void * arg0;
  } obsd41_sigreturn_compat42_args_t;

/* syscall: "adjtime" ret: "word" args: "ptr" "ptr" */
typedef uint32_t obsd41_adjtime_result_t;
typedef struct __obsd41_adjtime_args
  {
    void * arg0;
    void * arg1;
  } obsd41_adjtime_args_t;

/* syscall: "getpeername_compat43" ret: "word" args: "ptr" "word" */
typedef uint32_t obsd41_getpeername_compat43_result_t;
typedef struct __obsd41_getpeername_compat43_args
  {
    void * arg0;
    uint32_t arg1;
  } obsd41_getpeername_compat43_args_t;

/* syscall: "gethostid_compat43" ret: "word" args: "ptr" "word" */
typedef uint32_t obsd41_gethostid_compat43_result_t;
typedef struct __obsd41_gethostid_compat43_args
  {
    void * arg0;
    uint32_t arg1;
  } obsd41_gethostid_compat43_args_t;

/* syscall: "sethostid_compat43" ret: "word" args: "ptr" */
typedef uint32_t obsd41_sethostid_compat43_result_t;
typedef struct __obsd41_sethostid_compat43_args
  {
    void * arg0;
  } obsd41_sethostid_compat43_args_t;

/* syscall: "getrlimit_compat43" ret: "word" args: "word" "ptr" */
typedef uint32_t obsd41_getrlimit_compat43_result_t;
typedef struct __obsd41_getrlimit_compat43_args
  {
    uint32_t arg0;
    void * arg1;
  } obsd41_getrlimit_compat43_args_t;

/* syscall: "setrlimit_compat43" ret: "word" args: "word" "ptr" */
typedef uint32_t obsd41_setrlimit_compat43_result_t;
typedef struct __obsd41_setrlimit_compat43_args
  {
    uint32_t arg0;
    void * arg1;
  } obsd41_setrlimit_compat43_args_t;

/* syscall: "killpg_compat43" ret: "word" args: "word" "word" */
typedef uint32_t obsd41_killpg_compat43_result_t;
typedef struct __obsd41_killpg_compat43_args
  {
    uint32_t arg0;
    uint32_t arg1;
  } obsd41_killpg_compat43_args_t;

/* syscall: "setsid" ret: "word" args: */
typedef uint32_t obsd41_setsid_result_t;
typedef struct __obsd41_setsid_args
  {
    int dummy;
  } obsd41_setsid_args_t;

/* syscall: "quotactl" ret: "word" args: "ptr" "word" "word" "ptr" */
typedef uint32_t obsd41_quotactl_result_t;
typedef struct __obsd41_quotactl_args
  {
    void * arg0;
    uint32_t arg1;
    uint32_t arg2;
    void * arg3;
  } obsd41_quotactl_args_t;

/* syscall: "quota_compat43" ret: "word" args: */
typedef uint32_t obsd41_quota_compat43_result_t;
typedef struct __obsd41_quota_compat43_args
  {
    int dummy;
  } obsd41_quota_compat43_args_t;

/* syscall: "getsockname_compat43" ret: "word" args: "ptr" "word" */
typedef uint32_t obsd41_getsockname_compat43_result_t;
typedef struct __obsd41_getsockname_compat43_args
  {
    void * arg0;
    uint32_t arg1;
  } obsd41_getsockname_compat43_args_t;

/* syscall: "nfssvc" ret: "word" args: "word" "ptr" */
typedef uint32_t obsd41_nfssvc_result_t;
typedef struct __obsd41_nfssvc_args
  {
    uint32_t arg0;
    void * arg1;
  } obsd41_nfssvc_args_t;

/* syscall: "getdirentries_compat43" ret: "word" args: */
typedef uint32_t obsd41_getdirentries_compat43_result_t;
typedef struct __obsd41_getdirentries_compat43_args
  {
    int dummy;
  } obsd41_getdirentries_compat43_args_t;

/* syscall: "statfs_compat25" ret: "word" args: */
typedef uint32_t obsd41_statfs_compat25_result_t;
typedef struct __obsd41_statfs_compat25_args
  {
    int dummy;
  } obsd41_statfs_compat25_args_t;

/* syscall: "statfs_compat26" ret: "word" args: */
typedef uint32_t obsd41_statfs_compat26_result_t;
typedef struct __obsd41_statfs_compat26_args
  {
    int dummy;
  } obsd41_statfs_compat26_args_t;

/* syscall: "getfh" ret: "word" args: "ptr" "ptr" */
typedef uint32_t obsd41_getfh_result_t;
typedef struct __obsd41_getfh_args
  {
    void * arg0;
    void * arg1;
  } obsd41_getfh_args_t;

/* syscall: "getdomainname_compat09" ret: "word" args: "ptr" "word" */
typedef uint32_t obsd41_getdomainname_compat09_result_t;
typedef struct __obsd41_getdomainname_compat09_args
  {
    void * arg0;
    uint32_t arg1;
  } obsd41_getdomainname_compat09_args_t;

/* syscall: "setdomainname_compat09" ret: "word" args: "ptr" "word" */
typedef uint32_t obsd41_setdomainname_compat09_result_t;
typedef struct __obsd41_setdomainname_compat09_args
  {
    void * arg0;
    uint32_t arg1;
  } obsd41_setdomainname_compat09_args_t;

/* syscall: "uname_compat09" ret: "word" args: "ptr" */
typedef uint32_t obsd41_uname_compat09_result_t;
typedef struct __obsd41_uname_compat09_args
  {
    void * arg0;
  } obsd41_uname_compat09_args_t;

/* syscall: "sysarch" ret: "word" args: "word" "ptr" */
typedef uint32_t obsd41_sysarch_result_t;
typedef struct __obsd41_sysarch_args
  {
    uint32_t arg0;
    void * arg1;
  } obsd41_sysarch_args_t;

/* syscall: "semsys_compat10" ret: "word" args: */
typedef uint32_t obsd41_semsys_compat10_result_t;
typedef struct __obsd41_semsys_compat10_args
  {
    int dummy;
  } obsd41_semsys_compat10_args_t;

/* syscall: "msgsys_compat10" ret: "word" args: */
typedef uint32_t obsd41_msgsys_compat10_result_t;
typedef struct __obsd41_msgsys_compat10_args
  {
    int dummy;
  } obsd41_msgsys_compat10_args_t;

/* syscall: "shmsys_compat10" ret: "word" args: */
typedef uint32_t obsd41_shmsys_compat10_result_t;
typedef struct __obsd41_shmsys_compat10_args
  {
    int dummy;
  } obsd41_shmsys_compat10_args_t;

/* syscall: "pread" ret: "word" args: "word" "ptr" "word" "word" "dword" */
typedef uint32_t obsd41_pread_result_t;
typedef struct __obsd41_pread_args
  {
    uint32_t arg0;
    void * arg1;
    uint32_t arg2;
    uint32_t arg3;
    uint64_t arg4;
  } obsd41_pread_args_t;

/* syscall: "pwrite" ret: "word" args: "word" "ptr" "word" "word" "dword" */
typedef uint32_t obsd41_pwrite_result_t;
typedef struct __obsd41_pwrite_args
  {
    uint32_t arg0;
    void * arg1;
    uint32_t arg2;
    uint32_t arg3;
    uint64_t arg4;
  } obsd41_pwrite_args_t;

/* syscall: "setgid" ret: "word" args: "word" */
typedef uint32_t obsd41_setgid_result_t;
typedef struct __obsd41_setgid_args
  {
    uint32_t arg0;
  } obsd41_setgid_args_t;

/* syscall: "setegid" ret: "word" args: "word" */
typedef uint32_t obsd41_setegid_result_t;
typedef struct __obsd41_setegid_args
  {
    uint32_t arg0;
  } obsd41_setegid_args_t;

/* syscall: "seteuid" ret: "word" args: "word" */
typedef uint32_t obsd41_seteuid_result_t;
typedef struct __obsd41_seteuid_args
  {
    uint32_t arg0;
  } obsd41_seteuid_args_t;

/* syscall: "lfs_bmapv" ret: "word" args: "ptr" "ptr" "word" */
typedef uint32_t obsd41_lfs_bmapv_result_t;
typedef struct __obsd41_lfs_bmapv_args
  {
    void * arg0;
    void * arg1;
    uint32_t arg2;
  } obsd41_lfs_bmapv_args_t;

/* syscall: "lfs_markv" ret: "word" args: "ptr" "ptr" "word" */
typedef uint32_t obsd41_lfs_markv_result_t;
typedef struct __obsd41_lfs_markv_args
  {
    void * arg0;
    void * arg1;
    uint32_t arg2;
  } obsd41_lfs_markv_args_t;

/* syscall: "lfs_segclean" ret: "word" args: "ptr" "intptr" */
typedef uint32_t obsd41_lfs_segclean_result_t;
typedef struct __obsd41_lfs_segclean_args
  {
    void * arg0;
    uint32_t arg1;
  } obsd41_lfs_segclean_args_t;

/* syscall: "lfs_segwait" ret: "word" args: "ptr" "ptr" */
typedef uint32_t obsd41_lfs_segwait_result_t;
typedef struct __obsd41_lfs_segwait_args
  {
    void * arg0;
    void * arg1;
  } obsd41_lfs_segwait_args_t;

/* syscall: "stat_compat35" ret: "word" args: "word" "ptr" */
typedef uint32_t obsd41_stat_compat35_result_t;
typedef struct __obsd41_stat_compat35_args
  {
    uint32_t arg0;
    void * arg1;
  } obsd41_stat_compat35_args_t;

/* syscall: "fstat_compat35" ret: "word" args: "word" "ptr" */
typedef uint32_t obsd41_fstat_compat35_result_t;
typedef struct __obsd41_fstat_compat35_args
  {
    uint32_t arg0;
    void * arg1;
  } obsd41_fstat_compat35_args_t;

/* syscall: "lstat_compat35" ret: "word" args: "word" "ptr" */
typedef uint32_t obsd41_lstat_compat35_result_t;
typedef struct __obsd41_lstat_compat35_args
  {
    uint32_t arg0;
    void * arg1;
  } obsd41_lstat_compat35_args_t;

/* syscall: "pathconf" ret: "intptr" args: "ptr" "word" */
typedef uint32_t obsd41_pathconf_result_t;
typedef struct __obsd41_pathconf_args
  {
    void * arg0;
    uint32_t arg1;
  } obsd41_pathconf_args_t;

/* syscall: "fpathconf" ret: "intptr" args: "word" "word" */
typedef uint32_t obsd41_fpathconf_result_t;
typedef struct __obsd41_fpathconf_args
  {
    uint32_t arg0;
    uint32_t arg1;
  } obsd41_fpathconf_args_t;

/* syscall: "swapctl" ret: "word" args: "word" "ptr" "word" */
typedef uint32_t obsd41_swapctl_result_t;
typedef struct __obsd41_swapctl_args
  {
    uint32_t arg0;
    void * arg1;
    uint32_t arg2;
  } obsd41_swapctl_args_t;

/* syscall: "getrlimit" ret: "word" args: "word" "ptr" */
typedef uint32_t obsd41_getrlimit_result_t;
typedef struct __obsd41_getrlimit_args
  {
    uint32_t arg0;
    void * arg1;
  } obsd41_getrlimit_args_t;

/* syscall: "setrlimit" ret: "word" args: "word" "ptr" */
typedef uint32_t obsd41_setrlimit_result_t;
typedef struct __obsd41_setrlimit_args
  {
    uint32_t arg0;
    void * arg1;
  } obsd41_setrlimit_args_t;

/* syscall: "getdirentries" ret: "word" args: "word" "ptr" "word" "ptr" */
typedef uint32_t obsd41_getdirentries_result_t;
typedef struct __obsd41_getdirentries_args
  {
    uint32_t arg0;
    void * arg1;
    uint32_t arg2;
    void * arg3;
  } obsd41_getdirentries_args_t;

/* syscall: "mmap" ret: "intptr" args: "intptr" "word" "word" "word" "word" "intptr" "dword" */
typedef uint32_t obsd41_mmap_result_t;
typedef struct __obsd41_mmap_args
  {
    uint32_t arg0;
    uint32_t arg1;
    uint32_t arg2;
    uint32_t arg3;
    uint32_t arg4;
    uint32_t arg5;
    uint64_t arg6;
  } obsd41_mmap_args_t;

/* syscall: "__syscall" ret: "dword" args: "dword" "..." */
typedef uint64_t obsd41___syscall_result_t;
typedef struct __obsd41___syscall_args
  {
    uint64_t arg0;
    xec_param_t const *ap;
  } obsd41___syscall_args_t;

/* syscall: "lseek" ret: "dword" args: "word" "word" "dword" "word" */
typedef uint64_t obsd41_lseek_result_t;
typedef struct __obsd41_lseek_args
  {
    uint32_t arg0;
    uint32_t arg1;
    uint64_t arg2;
    uint32_t arg3;
  } obsd41_lseek_args_t;

/* syscall: "truncate" ret: "word" args: "ptr" "dword" */
typedef uint32_t obsd41_truncate_result_t;
typedef struct __obsd41_truncate_args
  {
    void * arg0;
    uint64_t arg1;
  } obsd41_truncate_args_t;

/* syscall: "ftruncate" ret: "word" args: "word" "dword" */
typedef uint32_t obsd41_ftruncate_result_t;
typedef struct __obsd41_ftruncate_args
  {
    uint32_t arg0;
    uint64_t arg1;
  } obsd41_ftruncate_args_t;

/* syscall: "__sysctl" ret: "word" args: "ptr" "word" "ptr" "ptr" "ptr" "word" */
typedef uint32_t obsd41___sysctl_result_t;
typedef struct __obsd41___sysctl_args
  {
    void * arg0;
    uint32_t arg1;
    void * arg2;
    void * arg3;
    void * arg4;
    uint32_t arg5;
  } obsd41___sysctl_args_t;

/* syscall: "mlock" ret: "word" args: "ptr" "word" */
typedef uint32_t obsd41_mlock_result_t;
typedef struct __obsd41_mlock_args
  {
    void * arg0;
    uint32_t arg1;
  } obsd41_mlock_args_t;

/* syscall: "munlock" ret: "word" args: "ptr" "word" */
typedef uint32_t obsd41_munlock_result_t;
typedef struct __obsd41_munlock_args
  {
    void * arg0;
    uint32_t arg1;
  } obsd41_munlock_args_t;

/* syscall: "futimes" ret: "word" args: "word" "ptr" */
typedef uint32_t obsd41_futimes_result_t;
typedef struct __obsd41_futimes_args
  {
    uint32_t arg0;
    void * arg1;
  } obsd41_futimes_args_t;

/* syscall: "getpgid" ret: "word" args: "word" */
typedef uint32_t obsd41_getpgid_result_t;
typedef struct __obsd41_getpgid_args
  {
    uint32_t arg0;
  } obsd41_getpgid_args_t;

/* syscall: "xfspioctl" ret: "word" args: "word" "ptr" "word" "ptr" "word" */
typedef uint32_t obsd41_xfspioctl_result_t;
typedef struct __obsd41_xfspioctl_args
  {
    uint32_t arg0;
    void * arg1;
    uint32_t arg2;
    void * arg3;
    uint32_t arg4;
  } obsd41_xfspioctl_args_t;

/* syscall: "semctl_compat23" ret: "word" args: */
typedef uint32_t obsd41_semctl_compat23_result_t;
typedef struct __obsd41_semctl_compat23_args
  {
    int dummy;
  } obsd41_semctl_compat23_args_t;

/* syscall: "semget" ret: "word" args: "word" "word" "word" */
typedef uint32_t obsd41_semget_result_t;
typedef struct __obsd41_semget_args
  {
    uint32_t arg0;
    uint32_t arg1;
    uint32_t arg2;
  } obsd41_semget_args_t;

/* syscall: "semop_compat35" ret: "word" args: */
typedef uint32_t obsd41_semop_compat35_result_t;
typedef struct __obsd41_semop_compat35_args
  {
    int dummy;
  } obsd41_semop_compat35_args_t;

/* syscall: "osys_semconfig" ret: "word" args: */
typedef uint32_t obsd41_osys_semconfig_result_t;
typedef struct __obsd41_osys_semconfig_args
  {
    int dummy;
  } obsd41_osys_semconfig_args_t;

/* syscall: "msgctl_compat23" ret: "word" args: */
typedef uint32_t obsd41_msgctl_compat23_result_t;
typedef struct __obsd41_msgctl_compat23_args
  {
    int dummy;
  } obsd41_msgctl_compat23_args_t;

/* syscall: "msgget" ret: "word" args: "word" "word" */
typedef uint32_t obsd41_msgget_result_t;
typedef struct __obsd41_msgget_args
  {
    uint32_t arg0;
    uint32_t arg1;
  } obsd41_msgget_args_t;

/* syscall: "msgsnd" ret: "word" args: "word" "ptr" "word" "word" */
typedef uint32_t obsd41_msgsnd_result_t;
typedef struct __obsd41_msgsnd_args
  {
    uint32_t arg0;
    void * arg1;
    uint32_t arg2;
    uint32_t arg3;
  } obsd41_msgsnd_args_t;

/* syscall: "msgrcv" ret: "word" args: "word" "ptr" "word" "intptr" "word" */
typedef uint32_t obsd41_msgrcv_result_t;
typedef struct __obsd41_msgrcv_args
  {
    uint32_t arg0;
    void * arg1;
    uint32_t arg2;
    uint32_t arg3;
    uint32_t arg4;
  } obsd41_msgrcv_args_t;

/* syscall: "shmat" ret: "ptr" args: "word" "ptr" "word" */
typedef void * obsd41_shmat_result_t;
typedef struct __obsd41_shmat_args
  {
    uint32_t arg0;
    void * arg1;
    uint32_t arg2;
  } obsd41_shmat_args_t;

/* syscall: "shmctl_compat23" ret: "word" args: */
typedef uint32_t obsd41_shmctl_compat23_result_t;
typedef struct __obsd41_shmctl_compat23_args
  {
    int dummy;
  } obsd41_shmctl_compat23_args_t;

/* syscall: "shmdt" ret: "word" args: "ptr" */
typedef uint32_t obsd41_shmdt_result_t;
typedef struct __obsd41_shmdt_args
  {
    void * arg0;
  } obsd41_shmdt_args_t;

/* syscall: "shmget_compat35" ret: "word" args: */
typedef uint32_t obsd41_shmget_compat35_result_t;
typedef struct __obsd41_shmget_compat35_args
  {
    int dummy;
  } obsd41_shmget_compat35_args_t;

/* syscall: "clock_gettime" ret: "word" args: "word" "ptr" */
typedef uint32_t obsd41_clock_gettime_result_t;
typedef struct __obsd41_clock_gettime_args
  {
    uint32_t arg0;
    void * arg1;
  } obsd41_clock_gettime_args_t;

/* syscall: "clock_settime" ret: "word" args: "word" "ptr" */
typedef uint32_t obsd41_clock_settime_result_t;
typedef struct __obsd41_clock_settime_args
  {
    uint32_t arg0;
    void * arg1;
  } obsd41_clock_settime_args_t;

/* syscall: "clock_getres" ret: "word" args: "word" "ptr" */
typedef uint32_t obsd41_clock_getres_result_t;
typedef struct __obsd41_clock_getres_args
  {
    uint32_t arg0;
    void * arg1;
  } obsd41_clock_getres_args_t;

/* syscall: "nanosleep" ret: "word" args: "ptr" "ptr" */
typedef uint32_t obsd41_nanosleep_result_t;
typedef struct __obsd41_nanosleep_args
  {
    void * arg0;
    void * arg1;
  } obsd41_nanosleep_args_t;

/* syscall: "minherit" ret: "word" args: "ptr" "word" "word" */
typedef uint32_t obsd41_minherit_result_t;
typedef struct __obsd41_minherit_args
  {
    void * arg0;
    uint32_t arg1;
    uint32_t arg2;
  } obsd41_minherit_args_t;

/* syscall: "rfork" ret: "word" args: "word" */
typedef uint32_t obsd41_rfork_result_t;
typedef struct __obsd41_rfork_args
  {
    uint32_t arg0;
  } obsd41_rfork_args_t;

/* syscall: "poll" ret: "word" args: "ptr" "word" "word" */
typedef uint32_t obsd41_poll_result_t;
typedef struct __obsd41_poll_args
  {
    void * arg0;
    uint32_t arg1;
    uint32_t arg2;
  } obsd41_poll_args_t;

/* syscall: "issetugid" ret: "word" args: */
typedef uint32_t obsd41_issetugid_result_t;
typedef struct __obsd41_issetugid_args
  {
    int dummy;
  } obsd41_issetugid_args_t;

/* syscall: "lchown" ret: "word" args: "ptr" "word" "word" */
typedef uint32_t obsd41_lchown_result_t;
typedef struct __obsd41_lchown_args
  {
    void * arg0;
    uint32_t arg1;
    uint32_t arg2;
  } obsd41_lchown_args_t;

/* syscall: "getsid" ret: "word" args: "word" */
typedef uint32_t obsd41_getsid_result_t;
typedef struct __obsd41_getsid_args
  {
    uint32_t arg0;
  } obsd41_getsid_args_t;

/* syscall: "msync" ret: "word" args: "ptr" "word" "word" */
typedef uint32_t obsd41_msync_result_t;
typedef struct __obsd41_msync_args
  {
    void * arg0;
    uint32_t arg1;
    uint32_t arg2;
  } obsd41_msync_args_t;

/* syscall: "semctl_compat35" ret: "word" args: */
typedef uint32_t obsd41_semctl_compat35_result_t;
typedef struct __obsd41_semctl_compat35_args
  {
    int dummy;
  } obsd41_semctl_compat35_args_t;

/* syscall: "shmctl_compat35" ret: "word" args: */
typedef uint32_t obsd41_shmctl_compat35_result_t;
typedef struct __obsd41_shmctl_compat35_args
  {
    int dummy;
  } obsd41_shmctl_compat35_args_t;

/* syscall: "msgctl_compat35" ret: "word" args: */
typedef uint32_t obsd41_msgctl_compat35_result_t;
typedef struct __obsd41_msgctl_compat35_args
  {
    int dummy;
  } obsd41_msgctl_compat35_args_t;

/* syscall: "getfsstat" ret: "word" args: "ptr" "word" "word" */
typedef uint32_t obsd41_getfsstat_result_t;
typedef struct __obsd41_getfsstat_args
  {
    void * arg0;
    uint32_t arg1;
    uint32_t arg2;
  } obsd41_getfsstat_args_t;

/* syscall: "statfs" ret: "word" args: "ptr" "ptr" */
typedef uint32_t obsd41_statfs_result_t;
typedef struct __obsd41_statfs_args
  {
    void * arg0;
    void * arg1;
  } obsd41_statfs_args_t;

/* syscall: "fstatfs" ret: "word" args: "word" "ptr" */
typedef uint32_t obsd41_fstatfs_result_t;
typedef struct __obsd41_fstatfs_args
  {
    uint32_t arg0;
    void * arg1;
  } obsd41_fstatfs_args_t;

/* syscall: "pipe" ret: "word" args: "ptr" */
typedef uint32_t obsd41_pipe_result_t;
typedef struct __obsd41_pipe_args
  {
    void * arg0;
  } obsd41_pipe_args_t;

/* syscall: "fhopen" ret: "word" args: "ptr" "word" */
typedef uint32_t obsd41_fhopen_result_t;
typedef struct __obsd41_fhopen_args
  {
    void * arg0;
    uint32_t arg1;
  } obsd41_fhopen_args_t;

/* syscall: "fhstat_compat35" ret: "word" args: */
typedef uint32_t obsd41_fhstat_compat35_result_t;
typedef struct __obsd41_fhstat_compat35_args
  {
    int dummy;
  } obsd41_fhstat_compat35_args_t;

/* syscall: "fhstatfs" ret: "word" args: "ptr" "ptr" */
typedef uint32_t obsd41_fhstatfs_result_t;
typedef struct __obsd41_fhstatfs_args
  {
    void * arg0;
    void * arg1;
  } obsd41_fhstatfs_args_t;

/* syscall: "preadv" ret: "word" args: "word" "ptr" "word" "word" "dword" */
typedef uint32_t obsd41_preadv_result_t;
typedef struct __obsd41_preadv_args
  {
    uint32_t arg0;
    void * arg1;
    uint32_t arg2;
    uint32_t arg3;
    uint64_t arg4;
  } obsd41_preadv_args_t;

/* syscall: "pwritev" ret: "word" args: "word" "ptr" "word" "word" "dword" */
typedef uint32_t obsd41_pwritev_result_t;
typedef struct __obsd41_pwritev_args
  {
    uint32_t arg0;
    void * arg1;
    uint32_t arg2;
    uint32_t arg3;
    uint64_t arg4;
  } obsd41_pwritev_args_t;

/* syscall: "kqueue" ret: "word" args: */
typedef uint32_t obsd41_kqueue_result_t;
typedef struct __obsd41_kqueue_args
  {
    int dummy;
  } obsd41_kqueue_args_t;

/* syscall: "kevent" ret: "word" args: "word" "ptr" "word" "ptr" "word" "ptr" */
typedef uint32_t obsd41_kevent_result_t;
typedef struct __obsd41_kevent_args
  {
    uint32_t arg0;
    void * arg1;
    uint32_t arg2;
    void * arg3;
    uint32_t arg4;
    void * arg5;
  } obsd41_kevent_args_t;

/* syscall: "mlockall" ret: "word" args: "word" */
typedef uint32_t obsd41_mlockall_result_t;
typedef struct __obsd41_mlockall_args
  {
    uint32_t arg0;
  } obsd41_mlockall_args_t;

/* syscall: "munlockall" ret: "word" args: "word" */
typedef uint32_t obsd41_munlockall_result_t;
typedef struct __obsd41_munlockall_args
  {
    uint32_t arg0;
  } obsd41_munlockall_args_t;

/* syscall: "getpeereid" ret: "word" args: "word" "ptr" "ptr" */
typedef uint32_t obsd41_getpeereid_result_t;
typedef struct __obsd41_getpeereid_args
  {
    uint32_t arg0;
    void * arg1;
    void * arg2;
  } obsd41_getpeereid_args_t;

/* syscall: "getresuid" ret: "word" args: "ptr" "ptr" "ptr" */
typedef uint32_t obsd41_getresuid_result_t;
typedef struct __obsd41_getresuid_args
  {
    void * arg0;
    void * arg1;
    void * arg2;
  } obsd41_getresuid_args_t;

/* syscall: "setresuid" ret: "word" args: "word" "word" "word" */
typedef uint32_t obsd41_setresuid_result_t;
typedef struct __obsd41_setresuid_args
  {
    uint32_t arg0;
    uint32_t arg1;
    uint32_t arg2;
  } obsd41_setresuid_args_t;

/* syscall: "getresgid" ret: "word" args: "ptr" "ptr" "ptr" */
typedef uint32_t obsd41_getresgid_result_t;
typedef struct __obsd41_getresgid_args
  {
    void * arg0;
    void * arg1;
    void * arg2;
  } obsd41_getresgid_args_t;

/* syscall: "setresgid" ret: "word" args: "word" "word" "word" */
typedef uint32_t obsd41_setresgid_result_t;
typedef struct __obsd41_setresgid_args
  {
    uint32_t arg0;
    uint32_t arg1;
    uint32_t arg2;
  } obsd41_setresgid_args_t;

/* syscall: "osys_mquery" ret: "word" args: */
typedef uint32_t obsd41_osys_mquery_result_t;
typedef struct __obsd41_osys_mquery_args
  {
    int dummy;
  } obsd41_osys_mquery_args_t;

/* syscall: "mquery" ret: "ptr" args: "ptr" "word" "word" "word" "intptr" "dword" */
typedef void * obsd41_mquery_result_t;
typedef struct __obsd41_mquery_args
  {
    void * arg0;
    uint32_t arg1;
    uint32_t arg2;
    uint32_t arg3;
    uint32_t arg4;
    uint64_t arg5;
  } obsd41_mquery_args_t;

/* syscall: "closefrom" ret: "word" args: "word" */
typedef uint32_t obsd41_closefrom_result_t;
typedef struct __obsd41_closefrom_args
  {
    uint32_t arg0;
  } obsd41_closefrom_args_t;

/* syscall: "sigaltstack" ret: "word" args: "ptr" "ptr" */
typedef uint32_t obsd41_sigaltstack_result_t;
typedef struct __obsd41_sigaltstack_args
  {
    void * arg0;
    void * arg1;
  } obsd41_sigaltstack_args_t;

/* syscall: "shmget" ret: "word" args: "word" "word" */
typedef uint32_t obsd41_shmget_result_t;
typedef struct __obsd41_shmget_args
  {
    uint32_t arg0;
    uint32_t arg1;
  } obsd41_shmget_args_t;

/* syscall: "semop" ret: "word" args: "word" "ptr" "word" */
typedef uint32_t obsd41_semop_result_t;
typedef struct __obsd41_semop_args
  {
    uint32_t arg0;
    void * arg1;
    uint32_t arg2;
  } obsd41_semop_args_t;

/* syscall: "stat" ret: "word" args: "ptr" "ptr" */
typedef uint32_t obsd41_stat_result_t;
typedef struct __obsd41_stat_args
  {
    void * arg0;
    void * arg1;
  } obsd41_stat_args_t;

/* syscall: "fstat" ret: "word" args: "word" "ptr" */
typedef uint32_t obsd41_fstat_result_t;
typedef struct __obsd41_fstat_args
  {
    uint32_t arg0;
    void * arg1;
  } obsd41_fstat_args_t;

/* syscall: "lstat" ret: "word" args: "ptr" "ptr" */
typedef uint32_t obsd41_lstat_result_t;
typedef struct __obsd41_lstat_args
  {
    void * arg0;
    void * arg1;
  } obsd41_lstat_args_t;

/* syscall: "fhstat" ret: "word" args: "ptr" "ptr" */
typedef uint32_t obsd41_fhstat_result_t;
typedef struct __obsd41_fhstat_args
  {
    void * arg0;
    void * arg1;
  } obsd41_fhstat_args_t;

/* syscall: "__semctl" ret: "word" args: "word" "word" "word" "ptr" */
typedef uint32_t obsd41___semctl_result_t;
typedef struct __obsd41___semctl_args
  {
    uint32_t arg0;
    uint32_t arg1;
    uint32_t arg2;
    void * arg3;
  } obsd41___semctl_args_t;

/* syscall: "shmctl" ret: "word" args: "word" "word" "ptr" */
typedef uint32_t obsd41_shmctl_result_t;
typedef struct __obsd41_shmctl_args
  {
    uint32_t arg0;
    uint32_t arg1;
    void * arg2;
  } obsd41_shmctl_args_t;

/* syscall: "msgctl" ret: "word" args: "word" "word" "ptr" */
typedef uint32_t obsd41_msgctl_result_t;
typedef struct __obsd41_msgctl_args
  {
    uint32_t arg0;
    uint32_t arg1;
    void * arg2;
  } obsd41_msgctl_args_t;

/* syscall: "sched_yield" ret: "word" args: */
typedef uint32_t obsd41_sched_yield_result_t;
typedef struct __obsd41_sched_yield_args
  {
    int dummy;
  } obsd41_sched_yield_args_t;

/* syscall: "getthrid" ret: "word" args: */
typedef uint32_t obsd41_getthrid_result_t;
typedef struct __obsd41_getthrid_args
  {
    int dummy;
  } obsd41_getthrid_args_t;

/* syscall: "thrsleep" ret: "word" args: "ptr" "word" "ptr" */
typedef uint32_t obsd41_thrsleep_result_t;
typedef struct __obsd41_thrsleep_args
  {
    void * arg0;
    uint32_t arg1;
    void * arg2;
  } obsd41_thrsleep_args_t;

/* syscall: "thrwakeup" ret: "word" args: "ptr" "word" */
typedef uint32_t obsd41_thrwakeup_result_t;
typedef struct __obsd41_thrwakeup_args
  {
    void * arg0;
    uint32_t arg1;
  } obsd41_thrwakeup_args_t;

/* syscall: "threxit" ret: "word" args: "word" */
typedef uint32_t obsd41_threxit_result_t;
typedef struct __obsd41_threxit_args
  {
    uint32_t arg0;
  } obsd41_threxit_args_t;

/* syscall: "thrsigdivert" ret: "word" args: "word" "word" */
typedef uint32_t obsd41_thrsigdivert_result_t;
typedef struct __obsd41_thrsigdivert_args
  {
    uint32_t arg0;
    uint32_t arg1;
  } obsd41_thrsigdivert_args_t;

/* syscall: "__getcwd" ret: "word" args: "ptr" "word" */
typedef uint32_t obsd41___getcwd_result_t;
typedef struct __obsd41___getcwd_args
  {
    void * arg0;
    uint32_t arg1;
  } obsd41___getcwd_args_t;

/* syscall: "adjfreq" ret: "word" args: "ptr" "ptr" */
typedef uint32_t obsd41_adjfreq_result_t;
typedef struct __obsd41_adjfreq_args
  {
    void * arg0;
    void * arg1;
  } obsd41_adjfreq_args_t;


#endif  /* !__obsd41_args_h */
