# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/local/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/op/work/ukatemi/libcpu

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/op/work/ukatemi/libcpu

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/op/work/ukatemi/libcpu/CMakeFiles /home/op/work/ukatemi/libcpu/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/op/work/ukatemi/libcpu/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 6502

# Build rule for target.
6502: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 6502
.PHONY : 6502

# fast build rule for target.
6502/fast:
	$(MAKE) -f arch/6502/CMakeFiles/6502.dir/build.make arch/6502/CMakeFiles/6502.dir/build
.PHONY : 6502/fast

#=============================================================================
# Target rules for targets named test_6502

# Build rule for target.
test_6502: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_6502
.PHONY : test_6502

# fast build rule for target.
test_6502/fast:
	$(MAKE) -f test/6502/CMakeFiles/test_6502.dir/build.make test/6502/CMakeFiles/test_6502.dir/build
.PHONY : test_6502/fast

#=============================================================================
# Target rules for targets named m68k

# Build rule for target.
m68k: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 m68k
.PHONY : m68k

# fast build rule for target.
m68k/fast:
	$(MAKE) -f arch/m68k/CMakeFiles/m68k.dir/build.make arch/m68k/CMakeFiles/m68k.dir/build
.PHONY : m68k/fast

#=============================================================================
# Target rules for targets named test_m68k

# Build rule for target.
test_m68k: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_m68k
.PHONY : test_m68k

# fast build rule for target.
test_m68k/fast:
	$(MAKE) -f test/m68k/CMakeFiles/test_m68k.dir/build.make test/m68k/CMakeFiles/test_m68k.dir/build
.PHONY : test_m68k/fast

#=============================================================================
# Target rules for targets named m88k

# Build rule for target.
m88k: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 m88k
.PHONY : m88k

# fast build rule for target.
m88k/fast:
	$(MAKE) -f arch/m88k/CMakeFiles/m88k.dir/build.make arch/m88k/CMakeFiles/m88k.dir/build
.PHONY : m88k/fast

#=============================================================================
# Target rules for targets named test_m88k

# Build rule for target.
test_m88k: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_m88k
.PHONY : test_m88k

# fast build rule for target.
test_m88k/fast:
	$(MAKE) -f test/m88k/CMakeFiles/test_m88k.dir/build.make test/m88k/CMakeFiles/test_m88k.dir/build
.PHONY : test_m88k/fast

#=============================================================================
# Target rules for targets named mips

# Build rule for target.
mips: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mips
.PHONY : mips

# fast build rule for target.
mips/fast:
	$(MAKE) -f arch/mips/CMakeFiles/mips.dir/build.make arch/mips/CMakeFiles/mips.dir/build
.PHONY : mips/fast

#=============================================================================
# Target rules for targets named test_mips

# Build rule for target.
test_mips: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_mips
.PHONY : test_mips

# fast build rule for target.
test_mips/fast:
	$(MAKE) -f test/mips/CMakeFiles/test_mips.dir/build.make test/mips/CMakeFiles/test_mips.dir/build
.PHONY : test_mips/fast

#=============================================================================
# Target rules for targets named arm

# Build rule for target.
arm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 arm
.PHONY : arm

# fast build rule for target.
arm/fast:
	$(MAKE) -f arch/arm/CMakeFiles/arm.dir/build.make arch/arm/CMakeFiles/arm.dir/build
.PHONY : arm/fast

#=============================================================================
# Target rules for targets named test_arm

# Build rule for target.
test_arm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_arm
.PHONY : test_arm

# fast build rule for target.
test_arm/fast:
	$(MAKE) -f test/arm/CMakeFiles/test_arm.dir/build.make test/arm/CMakeFiles/test_arm.dir/build
.PHONY : test_arm/fast

#=============================================================================
# Target rules for targets named x86

# Build rule for target.
x86: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 x86
.PHONY : x86

# fast build rule for target.
x86/fast:
	$(MAKE) -f arch/x86/CMakeFiles/x86.dir/build.make arch/x86/CMakeFiles/x86.dir/build
.PHONY : x86/fast

#=============================================================================
# Target rules for targets named test_run86

# Build rule for target.
test_run86: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_run86
.PHONY : test_run86

# fast build rule for target.
test_run86/fast:
	$(MAKE) -f test/x86/CMakeFiles/test_run86.dir/build.make test/x86/CMakeFiles/test_run86.dir/build
.PHONY : test_run86/fast

#=============================================================================
# Target rules for targets named i386

# Build rule for target.
i386: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 i386
.PHONY : i386

# fast build rule for target.
i386/fast:
	$(MAKE) -f arch/i386/CMakeFiles/i386.dir/build.make arch/i386/CMakeFiles/i386.dir/build
.PHONY : i386/fast

#=============================================================================
# Target rules for targets named test_i386

# Build rule for target.
test_i386: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_i386
.PHONY : test_i386

# fast build rule for target.
test_i386/fast:
	$(MAKE) -f test/i386/CMakeFiles/test_i386.dir/build.make test/i386/CMakeFiles/test_i386.dir/build
.PHONY : test_i386/fast

#=============================================================================
# Target rules for targets named fapra

# Build rule for target.
fapra: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fapra
.PHONY : fapra

# fast build rule for target.
fapra/fast:
	$(MAKE) -f arch/fapra/CMakeFiles/fapra.dir/build.make arch/fapra/CMakeFiles/fapra.dir/build
.PHONY : fapra/fast

#=============================================================================
# Target rules for targets named test_fib

# Build rule for target.
test_fib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_fib
.PHONY : test_fib

# fast build rule for target.
test_fib/fast:
	$(MAKE) -f test/multi/CMakeFiles/test_fib.dir/build.make test/multi/CMakeFiles/test_fib.dir/build
.PHONY : test_fib/fast

#=============================================================================
# Target rules for targets named cpu

# Build rule for target.
cpu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cpu
.PHONY : cpu

# fast build rule for target.
cpu/fast:
	$(MAKE) -f libcpu/CMakeFiles/cpu.dir/build.make libcpu/CMakeFiles/cpu.dir/build
.PHONY : cpu/fast

#=============================================================================
# Target rules for targets named upcc

# Build rule for target.
upcc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 upcc
.PHONY : upcc

# fast build rule for target.
upcc/fast:
	$(MAKE) -f upcl/CMakeFiles/upcc.dir/build.make upcl/CMakeFiles/upcc.dir/build
.PHONY : upcc/fast

#=============================================================================
# Target rules for targets named libloader

# Build rule for target.
libloader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libloader
.PHONY : libloader

# fast build rule for target.
libloader/fast:
	$(MAKE) -f test/libloader/CMakeFiles/libloader.dir/build.make test/libloader/CMakeFiles/libloader.dir/build
.PHONY : libloader/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... 6502"
	@echo "... test_6502"
	@echo "... m68k"
	@echo "... test_m68k"
	@echo "... m88k"
	@echo "... test_m88k"
	@echo "... mips"
	@echo "... test_mips"
	@echo "... arm"
	@echo "... test_arm"
	@echo "... x86"
	@echo "... test_run86"
	@echo "... i386"
	@echo "... test_i386"
	@echo "... fapra"
	@echo "... test_fib"
	@echo "... cpu"
	@echo "... upcc"
	@echo "... libloader"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

