#cmakedefine HAVE_SYS_RESOURCE_H ${HAVE_SYS_RESOURCE_H}
#cmakedefine HAVE_GETRUSAGE ${HAVE_GETRUSAGE}

#cmakedefine HAVE_ATTRIBUTE_PACKED ${HAVE_ATTRIBUTE_PACKED}
#cmakedefine HAVE_PRAGMA_PACK ${HAVE_PRAGMA_PACK}
#cmakedefine HAVE_ATTRIBUTE_ALIGNED ${HAVE_ATTRIBUTE_ALIGNED}
#cmakedefine HAVE_DECLSPEC_ALIGN ${HAVE_DECLSPEC_ALIGN}
#cmakedefine HAVE_DECLSPEC_DLLEXPORT ${HAVE_DECLSPEC_DLLEXPORT}
#cmakedefine HAVE_LIBREADLINE ${HAVE_LIBREADLINE}
#cmakedefine HAVE_NETINET_IN_H ${HAVE_NETINET_IN_H}

#cmakedefine HAVE_LIBRT ${HAVE_LIBRT}
