/*
 * libcpu: i386_arch.h
 * 
 * !!! DO NOT EDIT THIS FILE !!!
 * 
 * THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY UPCC
 */

#ifndef __i386_arch_h__
#define __i386_arch_h__

#include <assert.h>

#include "libcpu/libcpu.h"
#include "libcpu/fp_types.h"
#include "libcpu/frontend.h"

#include "i386_regfile.h"
#include "i386_disasm.h"

int arch_i386_tag_instr(cpu_t *cpu, addr_t pc, tag_t *tag, addr_t *new_pc, addr_t *next_pc);
llvm::Value *arch_i386_translate_cond(cpu_t *cpu, addr_t pc, llvm::BasicBlock *bb);
int arch_i386_disasm_instr(cpu_t *cpu, addr_t pc, char *line, unsigned int max_line);
int arch_i386_translate_instr(cpu_t *cpu, addr_t pc, llvm::BasicBlock *bb);

extern arch_func_t const arch_func_i386;

#endif  /* __i386_arch_h__ */
